# Sourced by agentic-team. Capability package orchestration.

enabled_capability_names() {
    local raw="${AR_CAPABILITIES:-agentic-notes,experiment-log}"
    local capability

    raw="${raw//,/ }"
    for capability in $raw; do
        [[ -n "$capability" ]] || continue
        [[ "$capability" == "none" ]] && continue
        if [[ "$capability" =~ ^[A-Za-z0-9._-]+$ ]]; then
            printf '%s\n' "$capability"
        else
            echo "Warning: Ignoring invalid capability name: $capability" >&2
        fi
    done
}

capability_enabled() {
    local needle="$1"
    local capability

    for capability in $(enabled_capability_names); do
        [[ "$capability" == "$needle" ]] && return 0
    done
    return 1
}

capability_root() {
    local capability_name="$1"
    local root

    for root in \
        "$STATE_ROOT/repos/org-agentic-notes/capabilities/$capability_name" \
        "$SCRIPT_DIR/capabilities/$capability_name"
    do
        [[ -d "$root" ]] || continue
        printf '%s\n' "$root"
        return 0
    done

    return 1
}

capability_instruction_hook_path() {
    local capability_name="$1"
    local root

    if ! root="$(capability_root "$capability_name")"; then
        return 1
    fi
    if [[ -x "$root/hooks/instruction" ]]; then
        printf '%s\n' "$root/hooks/instruction"
        return 0
    fi
    return 1
}

capability_bin_host_paths() {
    local capability_name root bin_dir

    for capability_name in $(enabled_capability_names); do
        if root="$(capability_root "$capability_name")"; then
            bin_dir="$root/bin"
            [[ -d "$bin_dir" ]] && printf '%s\n' "$bin_dir"
        fi
    done
}

capability_runtime_root() {
    local capability_name="$1"
    local host_root="$2"

    if [[ "$host_root" == "$SCRIPT_DIR/capabilities/$capability_name" ]]; then
        printf '%s/capabilities/%s\n' "$(ar_install_env_path)" "$capability_name"
    else
        printf '%s\n' "$host_root"
    fi
}

capability_bin_runtime_paths() {
    local capability_name root runtime_root bin_dir

    for capability_name in $(enabled_capability_names); do
        if root="$(capability_root "$capability_name")"; then
            runtime_root="$(capability_runtime_root "$capability_name" "$root")"
            bin_dir="$runtime_root/bin"
            [[ -d "$root/bin" ]] && printf '%s\n' "$bin_dir"
        fi
    done
}

capability_instruction_call() {
    local capability_name="$1"
    shift
    local hook_exe

    if ! hook_exe="$(capability_instruction_hook_path "$capability_name")"; then
        return 0
    fi
    "$hook_exe" "$@"
}

project_agent_root_for_cli() {
    cli_call_required project_agent_root
}

CAPABILITY_SECTION_DIR=""

render_agentic_notes_for_agent_type() {
    local render_agent_type="$1"
    local rendered_path

    capability_enabled agentic-notes || return 0

    if [[ -n "$CAPABILITY_SECTION_DIR" ]]; then
        rendered_path="$CAPABILITY_SECTION_DIR/$render_agent_type.md"
        if [[ -f "$rendered_path" ]]; then
            cat "$rendered_path"
            return 0
        fi
    fi
    capability_instruction_call agentic-notes render-section \
        --project-dir "$WORKSPACE_DIR" \
        --agent-type "$render_agent_type" 2>/dev/null || true
}

prepare_capability_sections() {
    [[ ${#ACTIVE_PROJECT_AGENT_NAMES[@]} -gt 0 ]] || return 0
    capability_enabled agentic-notes || return 0

    local temp_root render_args agent_name
    temp_root="$STATE_ROOT/tmp"
    mkdir -p "$temp_root"
    CAPABILITY_SECTION_DIR="$(mktemp -d "$temp_root/capability-sections.XXXXXX")" || {
        CAPABILITY_SECTION_DIR=""
        return 0
    }

    render_args=(render-sections --project-dir "$WORKSPACE_DIR" --output-dir "$CAPABILITY_SECTION_DIR")
    for agent_name in "${ACTIVE_PROJECT_AGENT_NAMES[@]}"; do
        render_args+=(--agent-type "$agent_name")
    done

    if ! capability_instruction_call agentic-notes "${render_args[@]}" >/dev/null 2>/dev/null; then
        rm -rf "$CAPABILITY_SECTION_DIR"
        CAPABILITY_SECTION_DIR=""
    fi
}

cleanup_capability_sections() {
    if [[ -n "$CAPABILITY_SECTION_DIR" ]]; then
        rm -rf "$CAPABILITY_SECTION_DIR"
        CAPABILITY_SECTION_DIR=""
    fi
}

valid_agent_name() {
    [[ "$1" =~ ^[A-Za-z0-9._-]+$ ]]
}

render_markdown_agent_file() {
    local source_path="$1"
    local target_path="$2"
    local agent_name="$3"
    local temp_path="${target_path}.tmp"

    awk -v agent_name="$agent_name" '
        BEGIN { inserted=0; in_frontmatter=0 }
        NR == 1 && $0 == "---" { in_frontmatter=1; print; next }
        in_frontmatter && $0 ~ /^[[:space:]]*(kind|codex_reasoning_effort|model_reasoning_effort):[[:space:]]*/ { next }
        in_frontmatter && $0 == "---" {
            print
            print ""
            print "<!-- Generated by agentic-team. Edit the source agent definition to change this agent. -->"
            inserted=1
            in_frontmatter=0
            next
        }
        { print }
        END {
            if (inserted == 0) {
                print "<!-- Generated by agentic-team. Edit the source agent definition to change this agent. -->"
            }
        }
    ' "$source_path" | expand_modules_from_stdin > "$temp_path"
    {
        printf '\n'
        render_agentic_notes_for_agent_type "$agent_name"
    } >> "$temp_path"

    mv "$temp_path" "$target_path"
}

render_agent_for_cli() {
    cli_call_required render_agent "$@"
}

ACTIVE_PROJECT_AGENT_NAMES=()

add_active_project_agent_name() {
    local agent_name="$1"
    ACTIVE_PROJECT_AGENT_NAMES+=("$agent_name")
}

collect_active_project_agent_names() {
    local source_dir="$1"
    local override_dir="$2"
    local source_path agent_name kind

    [[ -d "$source_dir" ]] || return 0
    for source_path in "$source_dir"/*.md; do
        [[ -f "$source_path" ]] || continue
        agent_name="$(agent_name_for_source "$source_path")"
        if [[ -n "$override_dir" ]] && agent_name_exists_in_source_dir "$agent_name" "$override_dir"; then
            continue
        fi
        [[ -n "$agent_name" ]] || continue
        valid_agent_name "$agent_name" || continue
        kind="$(agent_kind_for_source "$source_path")"
        [[ "$kind" == "subagent" ]] || continue
        add_active_project_agent_name "$agent_name"
    done
}

is_active_project_agent_name() {
    local needle="$1"
    local agent_name

    for agent_name in "${ACTIVE_PROJECT_AGENT_NAMES[@]}"; do
        [[ "$agent_name" == "$needle" ]] && return 0
    done
    return 1
}

cleanup_inactive_managed_agents() {
    local agent_root="$1"
    local managed_marker="$2"
    local target_path target_file agent_name

    [[ -d "$agent_root" ]] || return 0
    for target_path in "$agent_root"/*; do
        [[ -f "$target_path" ]] || continue
        grep -q "$managed_marker" "$target_path" || continue
        target_file="$(basename "$target_path")"
        case "$target_file" in
            *.toml)
                agent_name="${target_file%.toml}"
                ;;
            *.md)
                agent_name="${target_file%.md}"
                ;;
            *)
                continue
                ;;
        esac
        if ! is_active_project_agent_name "$agent_name"; then
            rm -f "$target_path"
        fi
    done
}

render_agent_source_dir() {
    local agent_root="$1"
    local source_dir="$2"
    local source_label="$3"
    local kind_filter="$4"
    local override_dir="${5:-}"
    local managed_marker="Generated by agentic-team"
    local source_path agent_name kind description codex_reasoning_effort target_path

    [[ -d "$source_dir" ]] || return 0

    for source_path in "$source_dir"/*.md; do
        [[ -f "$source_path" ]] || continue
        agent_name="$(agent_name_for_source "$source_path")"
        if [[ -n "$override_dir" ]] && agent_name_exists_in_source_dir "$agent_name" "$override_dir"; then
            continue
        fi
        kind="$(agent_kind_for_source "$source_path")"
        if [[ "$kind" != "$kind_filter" ]]; then
            continue
        fi
        description="$(frontmatter_value "$source_path" "description")"
        codex_reasoning_effort="$(frontmatter_value "$source_path" "codex_reasoning_effort")"
        if [[ -z "$codex_reasoning_effort" ]]; then
            codex_reasoning_effort="$(frontmatter_value "$source_path" "model_reasoning_effort")"
        fi
        [[ -n "$description" ]] || description="$agent_name agent."

        if ! valid_agent_name "$agent_name"; then
            echo "Warning: Skipping $source_label agent with invalid name: $agent_name"
            continue
        fi

        target_path="$(cli_call_required agent_target_path "$agent_root" "$agent_name")"
        [[ -n "$target_path" ]] || continue

        if [[ -f "$target_path" ]] && ! grep -q "$managed_marker" "$target_path"; then
            echo "Warning: Skipping $source_label agent at $target_path (not managed by agentic-team)"
            continue
        fi

        render_agent_for_cli "$source_path" "$target_path" "$agent_name" "$description" "$codex_reasoning_effort"
    done
}

setup_project_agents() {
    local agent_root org_agent_dir=""
    local render_status=0
    agent_root="$(project_agent_root_for_cli)"
    [[ -n "$agent_root" ]] || return 0

    mkdir -p "$agent_root"

    if [[ -n "${AR_ORG_NOTES_REPO:-}" ]]; then
        org_agent_dir="$STATE_ROOT/repos/org-agentic-notes/agents"
    fi

    ACTIVE_PROJECT_AGENT_NAMES=()
    collect_active_project_agent_names "$SCRIPT_DIR/agents" "$org_agent_dir"
    collect_active_project_agent_names "$org_agent_dir" ""
    cleanup_inactive_managed_agents "$agent_root" "Generated by agentic-team"
    prepare_capability_sections

    if ! render_agent_source_dir "$agent_root" "$SCRIPT_DIR/agents" "built-in" "subagent" "$org_agent_dir"; then
        render_status=1
    fi

    if [[ -n "${AR_ORG_NOTES_REPO:-}" ]]; then
        if ! render_agent_source_dir "$agent_root" "$org_agent_dir" "org" "subagent"; then
            render_status=1
        fi
    fi

    cleanup_capability_sections
    return "$render_status"
}

render_skill_instruction_file() {
    local instruction_source="$1"

    [[ -f "$instruction_source" ]] || return 0

    cat "$instruction_source"
}

render_skill_instruction_parts() {
    local source_path skill_name capability_dir

    for skill_name in $(enabled_capability_names); do
        capability_dir="$(capability_root "$skill_name")" || continue
        source_path="$capability_dir/INSTRUCTIONS.md"
        render_skill_instruction_file "$source_path"
        printf '\n'
    done
}

export_capability_env() {
    if [[ -n "${AR_WORK_BRANCH_ID:-}" ]]; then
        AR_SESSION_ID="${AR_SESSION_ID:-$AR_PROJECT_ID-$AR_WORK_BRANCH_ID-$$-$(date +%s)}"
    fi

    export_ar_capability_env
}

setup_agentic_notes_capability_once() {
    capability_enabled agentic-notes || return 0
    [[ "$AGENTIC_NOTES_CAPABILITY_SETUP" == "true" ]] && return 0

    export_capability_env
    if ! capability_instruction_call agentic-notes setup \
        --project-dir "$WORKSPACE_DIR" \
        --branch "${WORKSPACE_GIT_BRANCH:-}" \
        --session-id "${AR_SESSION_ID:-}" \
        --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
        --cli "$AR_CLI"; then
        echo "Error: Capability 'agentic-notes' setup failed."
        exit 1
    fi
    AGENTIC_NOTES_CAPABILITY_SETUP=true
}

setup_capabilities() {
    local capability_name

    export_capability_env

    for capability_name in $(enabled_capability_names); do
        if [[ "$capability_name" == "agentic-notes" && "$AGENTIC_NOTES_CAPABILITY_SETUP" == "true" ]]; then
            continue
        fi
        if ! capability_instruction_call "$capability_name" setup \
            --project-dir "$WORKSPACE_DIR" \
            --branch "${WORKSPACE_GIT_BRANCH:-}" \
            --session-id "${AR_SESSION_ID:-}" \
            --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
            --cli "$AR_CLI"; then
            echo "Error: Capability '$capability_name' setup failed."
            exit 1
        fi
    done
}

cleanup_capabilities() {
    local capability_name

    export_ar_capability_env

    for capability_name in $(enabled_capability_names); do
        capability_instruction_call "$capability_name" cleanup \
            --project-dir "$WORKSPACE_DIR" \
            --branch "${WORKSPACE_GIT_BRANCH:-}" \
            --session-id "${AR_SESSION_ID:-}" \
            --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
            --cli "$AR_CLI" >/dev/null || true
    done
}

launcher_cleanup() {
    local status=$?
    trap - EXIT
    if [[ "$CAPABILITY_CLEANUP_ENABLED" == "true" ]]; then
        run_capability_launcher_hooks cleanup || true
    fi
    cleanup_capabilities || true
    cleanup_branch_guard || true
    return "$status"
}

setup_capability_refresh_loops() {
    [[ "$TEST_MODE" == "true" ]] && return 0
    [[ "$RENDER_ONLY" == "true" ]] && return 0

    case "${AR_NOTES_AUTO_REFRESH:-true}" in
        0|false|False|FALSE|no|No|NO|off|Off|OFF)
            return 0
            ;;
    esac

    case "${AR_NOTES_REFRESH_MODE:-periodic}" in
        periodic|background)
            ;;
        *)
            return 0
            ;;
    esac

    local interval heartbeat_period heartbeat_dir heartbeat_file refresh_log launcher_pid stale_seconds
    interval="${AR_NOTES_REFRESH_INTERVAL_SECONDS:-120}"
    if ! [[ "$interval" =~ ^[0-9]+$ ]] || [[ "$interval" -lt 1 ]]; then
        interval=120
    fi
    heartbeat_period=$((interval / 4))
    if [[ "$heartbeat_period" -lt 1 ]]; then
        heartbeat_period=1
    elif [[ "$heartbeat_period" -gt 30 ]]; then
        heartbeat_period=30
    fi
    stale_seconds=$((interval * 2))
    if [[ "$stale_seconds" -lt $((heartbeat_period * 3)) ]]; then
        stale_seconds=$((heartbeat_period * 3))
    fi

    heartbeat_dir="$STATE_ROOT/refresh-heartbeats/$AR_PROJECT_ID"
    heartbeat_file="$heartbeat_dir/$$.heartbeat"
    refresh_log="$STATE_ROOT/logs/agentic-notes-refresh-$AR_PROJECT_ID.log"
    launcher_pid="$$"
    mkdir -p "$heartbeat_dir" "$(dirname "$refresh_log")"
    touch "$heartbeat_file"

    (
        while kill -0 "$launcher_pid" 2>/dev/null; do
            touch "$heartbeat_file"
            sleep "$heartbeat_period"
        done
        rm -f "$heartbeat_file"
    ) >/dev/null 2>&1 &

    local capability_name
    for capability_name in $(enabled_capability_names); do
        capability_instruction_call "$capability_name" refresh-loop \
            --project-dir "$WORKSPACE_DIR" \
            --heartbeat-dir "$heartbeat_dir" \
            --interval-seconds "$interval" \
            --stale-seconds "$stale_seconds" \
            --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
            --cli "$AR_CLI" >>"$refresh_log" 2>&1 &
    done
}

render_capability_instruction_parts() {
    local capability_name section

    export_ar_capability_env

    for capability_name in $(enabled_capability_names); do
        section="$(
            capability_instruction_call "$capability_name" render-instruction \
                --project-dir "$WORKSPACE_DIR" \
                --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
                --cli "$AR_CLI" 2>/dev/null || true
        )"
        if [[ -n "$section" ]]; then
            printf '%s\n\n' "$section"
        fi
    done
}
