# Sourced by agentic-team. Compaction hook rendering and CLI argument translation.

merge_managed_hook_json() {
    local target_path="$1"
    local marker="$2"
    local patch_json="$3"

    mkdir -p "$(dirname "$target_path")"

    AR_HOOK_PATCH_JSON="$patch_json" python3 - "$target_path" "$marker" <<'PY'
import json
import os
import sys
from pathlib import Path

target = Path(sys.argv[1])
marker = sys.argv[2]
patch = json.loads(os.environ["AR_HOOK_PATCH_JSON"])

if target.exists():
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"{target}: invalid JSON ({exc})", file=sys.stderr)
        sys.exit(1)
else:
    data = {}

if not isinstance(data, dict):
    print(f"{target}: top-level JSON value must be an object", file=sys.stderr)
    sys.exit(1)

data_hooks = data.setdefault("hooks", {})
if not isinstance(data_hooks, dict):
    print(f"{target}: hooks must be an object", file=sys.stderr)
    sys.exit(1)

def is_managed_group(group):
    if not isinstance(group, dict):
        return False
    for hook in group.get("hooks", []):
        if not isinstance(hook, dict):
            continue
        fields = [
            hook.get("command", ""),
            hook.get("name", ""),
            hook.get("statusMessage", ""),
            hook.get("description", ""),
        ]
        if any(marker in str(field) for field in fields):
            return True
    return False

for event_name, groups in patch.get("hooks", {}).items():
    if not isinstance(groups, list):
        print(f"patch hooks.{event_name}: value must be an array", file=sys.stderr)
        sys.exit(1)
    existing = data_hooks.get(event_name, [])
    if not isinstance(existing, list):
        existing = []
    data_hooks[event_name] = [
        group for group in existing
        if not is_managed_group(group)
    ] + groups

target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
PY
}

render_compaction_context_hook_script() {
    local target_path="$1"
    local managed_marker="Generated by agentic-team"

    if [[ -f "$target_path" ]] && ! grep -q "$managed_marker" "$target_path"; then
        echo "Warning: Skipping existing compaction hook script at $target_path (not managed by agentic-team)"
        return 1
    fi

    mkdir -p "$(dirname "$target_path")"
    cat > "$target_path" <<'PY'
#!/usr/bin/env python3
# Generated by agentic-team. Edit the launcher to change this file.
import json
import subprocess
import sys
from pathlib import Path


def run_command(command: list[str]) -> tuple[bool, str]:
    try:
        result = subprocess.run(command, text=True, capture_output=True, timeout=60)
    except Exception as exc:
        return False, f"{command[0]} did not run: {exc}"
    output = (result.stdout or result.stderr or "").strip()
    if result.returncode == 0:
        return True, output
    return False, output or f"{command[0]} exited with status {result.returncode}."


def run_refresh(capability_refresh_cli: str, instruction_path: str, project_dir: str, agent_type: str, cli: str) -> tuple[bool, str]:
    if not capability_refresh_cli:
        return False, "capability-refresh was not configured."
    command = [
        capability_refresh_cli,
        "--instruction-path",
        instruction_path,
        "--project-dir",
        project_dir,
        "--agent-type",
        agent_type,
        "--cli",
        cli,
    ]
    return run_command(command)


def read_hook_input() -> dict:
    try:
        value = json.load(sys.stdin)
    except Exception:
        return {}
    return value if isinstance(value, dict) else {}


def refresh_message(instruction_path: str, capability_refresh_cli: str, project_dir: str, agent_type: str, cli: str) -> str:
    refreshed, refresh_status = run_refresh(capability_refresh_cli, instruction_path, project_dir, agent_type, cli)
    refresh_sentence = (
        "Agentic Team just refreshed configured capabilities and rematerialized the rendered instruction file."
        if refreshed
        else f"Agentic Team tried to refresh configured capabilities, but refresh failed: {refresh_status}"
    )
    return (
        "You have just experienced context compaction. Treat this moment as "
        "the new `since the last compaction` boundary for Agentic Notes. "
        f"{refresh_sentence} Before continuing, read "
        f"`{instruction_path}`, the instruction file rendered for this "
        "specific Agentic Team invocation, then continue with whatever "
        "task was in progress before compaction. Do not restart from scratch."
    )


def marker_path() -> Path:
    return Path(__file__).with_name(".agentic-team-compaction.pending")


def mark_pending(message: str) -> None:
    marker_path().write_text(json.dumps({"message": message}) + "\n", encoding="utf-8")


def inject_pending() -> None:
    read_hook_input()
    marker = marker_path()
    if not marker.exists():
        print("{}")
        return

    try:
        marker_data = json.loads(marker.read_text(encoding="utf-8"))
    except Exception:
        marker_data = {}
    try:
        marker.unlink()
    except FileNotFoundError:
        pass

    message = marker_data.get("message")
    if not isinstance(message, str) or not message:
        print("{}")
        return

    print(json.dumps({
        "suppressOutput": True,
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": message,
        },
    }))


def parse_args() -> tuple[str, str, str, str, str, str]:
    modes = {"session-start", "post-compact", "inject-pending"}
    if len(sys.argv) > 1 and sys.argv[1] in modes:
        mode = sys.argv[1]
        offset = 2
    else:
        mode = "session-start"
        offset = 1

    instruction_path = sys.argv[offset] if len(sys.argv) > offset else "AGENTS.md"
    capability_refresh_cli = sys.argv[offset + 1] if len(sys.argv) > offset + 1 else ""
    project_dir = sys.argv[offset + 2] if len(sys.argv) > offset + 2 else "."
    agent_type = sys.argv[offset + 3] if len(sys.argv) > offset + 3 else "research-coordinator"
    cli = sys.argv[offset + 4] if len(sys.argv) > offset + 4 else "codex"
    return mode, instruction_path, capability_refresh_cli, project_dir, agent_type, cli


def main() -> None:
    mode, instruction_path, capability_refresh_cli, project_dir, agent_type, cli = parse_args()
    if mode == "inject-pending":
        inject_pending()
        return

    hook_input = read_hook_input()
    event_name = hook_input.get("hook_event_name") or "SessionStart"
    message = refresh_message(instruction_path, capability_refresh_cli, project_dir, agent_type, cli)
    if mode == "post-compact":
        mark_pending(message)
        print(json.dumps({
            "systemMessage": message,
        }))
        return

    print(json.dumps({
        "systemMessage": "Agentic Team refreshed post-compaction instructions.",
        "hookSpecificOutput": {
            "hookEventName": event_name,
            "additionalContext": message,
        },
    }))


if __name__ == "__main__":
    main()
PY
    chmod +x "$target_path"
}

setup_compaction_hooks() {
    [[ -n "${INSTRUCTION_TARGET:-}" ]] || return 0

    PI_AGENTIC_COMPACTION_EXTENSION=""
    cli_call setup_compaction_hooks
}
translate_cli_args() {
    cli_call translate_cli_args
}
