# Sourced by agentic-researcher. Compaction hook rendering and tool argument translation.

merge_managed_hook_json() {
    local target_path="$1"
    local marker="$2"
    local patch_json="$3"

    mkdir -p "$(dirname "$target_path")"

    resolve_python_cmd || return 1
    AR_HOOK_PATCH_JSON="$patch_json" "${AR_PYTHON_CMD[@]}" - "$target_path" "$marker" <<'PY'
import json
import os
import sys
from pathlib import Path

target = Path(sys.argv[1])
marker = sys.argv[2]
patch = json.loads(os.environ["AR_HOOK_PATCH_JSON"])

if target.exists():
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"{target}: invalid JSON ({exc})", file=sys.stderr)
        sys.exit(1)
else:
    data = {}

if not isinstance(data, dict):
    print(f"{target}: top-level JSON value must be an object", file=sys.stderr)
    sys.exit(1)

data_hooks = data.setdefault("hooks", {})
if not isinstance(data_hooks, dict):
    print(f"{target}: hooks must be an object", file=sys.stderr)
    sys.exit(1)

def is_managed_group(group):
    if not isinstance(group, dict):
        return False
    for hook in group.get("hooks", []):
        if not isinstance(hook, dict):
            continue
        fields = [
            hook.get("command", ""),
            hook.get("name", ""),
            hook.get("statusMessage", ""),
            hook.get("description", ""),
        ]
        if any(marker in str(field) for field in fields):
            return True
    return False

for event_name, groups in patch.get("hooks", {}).items():
    if not isinstance(groups, list):
        print(f"patch hooks.{event_name}: value must be an array", file=sys.stderr)
        sys.exit(1)
    existing = data_hooks.get(event_name, [])
    if not isinstance(existing, list):
        existing = []
    data_hooks[event_name] = [
        group for group in existing
        if not is_managed_group(group)
    ] + groups

target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
PY
}

render_compaction_context_hook_script() {
    local target_path="$1"
    local managed_marker="Generated by agentic-researcher"

    if [[ -f "$target_path" ]] && ! grep -q "$managed_marker" "$target_path"; then
        echo "Warning: Skipping existing compaction hook script at $target_path (not managed by agentic-researcher)"
        return 1
    fi

    mkdir -p "$(dirname "$target_path")"
    cat > "$target_path" <<'PY'
#!/usr/bin/env python3
# Generated by agentic-researcher. Edit the launcher to change this file.
import json
import subprocess
import sys


def run_command(command: list[str]) -> tuple[bool, str]:
    try:
        result = subprocess.run(command, text=True, capture_output=True, timeout=60)
    except Exception as exc:
        return False, f"{command[0]} did not run: {exc}"
    output = (result.stdout or result.stderr or "").strip()
    if result.returncode == 0:
        return True, output
    return False, output or f"{command[0]} exited with status {result.returncode}."


def run_refresh(provider_refresh_cli: str, instruction_path: str, project_dir: str, agent_type: str, tool: str) -> tuple[bool, str]:
    if not provider_refresh_cli:
        return False, "AR_PROVIDER_REFRESH_CLI was not configured."
    command = [
        provider_refresh_cli,
        "--instruction-path",
        instruction_path,
        "--project-dir",
        project_dir,
        "--agent-type",
        agent_type,
        "--tool",
        tool,
    ]
    return run_command(command)


def main() -> None:
    instruction_path = sys.argv[1] if len(sys.argv) > 1 else "AGENTS.md"
    provider_refresh_cli = sys.argv[2] if len(sys.argv) > 2 else ""
    project_dir = sys.argv[3] if len(sys.argv) > 3 else "."
    agent_type = sys.argv[4] if len(sys.argv) > 4 else "research-coordinator"
    tool = sys.argv[5] if len(sys.argv) > 5 else "codex"
    try:
        hook_input = json.load(sys.stdin)
    except Exception:
        hook_input = {}
    event_name = hook_input.get("hook_event_name") or "SessionStart"
    refreshed, refresh_status = run_refresh(provider_refresh_cli, instruction_path, project_dir, agent_type, tool)
    refresh_sentence = (
        "Agentic Researcher just refreshed configured instruction providers and rematerialized the rendered instruction file."
        if refreshed
        else f"Agentic Researcher tried to refresh configured instruction providers, but refresh failed: {refresh_status}"
    )
    message = (
        "You have just experienced context compaction. Treat this moment as "
        "the new `since the last compaction` boundary for Agentic Notes. "
        f"{refresh_sentence} Before continuing, read "
        f"`{instruction_path}`, the instruction file rendered for this "
        "specific Agentic Researcher invocation, then continue with whatever "
        "task was in progress before compaction. Do not restart from scratch."
    )
    print(json.dumps({
        "systemMessage": "Agentic Researcher refreshed post-compaction instructions.",
        "hookSpecificOutput": {
            "hookEventName": event_name,
            "additionalContext": message,
        },
    }))


if __name__ == "__main__":
    main()
PY
    chmod +x "$target_path"
}

setup_compaction_hooks() {
    [[ -n "${INSTRUCTION_TARGET:-}" ]] || return 0

    PI_AGENTIC_COMPACTION_EXTENSION=""
    cli_call setup_compaction_hooks
}
translate_tool_args() {
    cli_call translate_tool_args
}
