# Sourced by agentic-researcher. Instruction provider orchestration and refresh loops.

enabled_provider_names() {
    local raw="${AR_INSTRUCTION_PROVIDERS:-agentic-notes,experiment-log}"
    local provider

    raw="${raw//,/ }"
    for provider in $raw; do
        [[ -n "$provider" ]] || continue
        [[ "$provider" == "none" ]] && continue
        if [[ "$provider" =~ ^[A-Za-z0-9._-]+$ ]]; then
            printf '%s\n' "$provider"
        else
            echo "Warning: Ignoring invalid instruction provider name: $provider" >&2
        fi
    done
}

provider_enabled() {
    local needle="$1"
    local provider

    for provider in $(enabled_provider_names); do
        [[ "$provider" == "$needle" ]] && return 0
    done
    return 1
}

provider_path() {
    local provider_name="$1"
    local candidate

    for candidate in \
        "$STATE_ROOT/repos/org-agentic-notes/providers/$provider_name/bin/$provider_name" \
        "$STATE_ROOT/repos/org-agentic-notes/providers/$provider_name/$provider_name" \
        "$SCRIPT_DIR/scripts/providers/$provider_name"
    do
        if [[ -x "$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done

    return 1
}

provider_call() {
    local provider_name="$1"
    shift
    local provider_exe

    if ! provider_exe="$(provider_path "$provider_name")"; then
        echo "Warning: Instruction provider not found: $provider_name" >&2
        return 127
    fi
    "$provider_exe" "$@"
}

project_agent_root_for_tool() {
    cli_call_required project_agent_root
}

PROVIDER_SECTION_DIR=""

render_agentic_notes_for_agent_type() {
    local render_agent_type="$1"
    local rendered_path

    provider_enabled agentic-notes || return 0

    if [[ -n "$PROVIDER_SECTION_DIR" ]]; then
        rendered_path="$PROVIDER_SECTION_DIR/$render_agent_type.md"
        if [[ -f "$rendered_path" ]]; then
            cat "$rendered_path"
            return 0
        fi
    fi
    provider_call agentic-notes render-section \
        --project-dir "$WORKSPACE_DIR" \
        --agent-type "$render_agent_type" 2>/dev/null || true
}

prepare_provider_sections() {
    [[ ${#ACTIVE_PROJECT_AGENT_NAMES[@]} -gt 0 ]] || return 0
    provider_enabled agentic-notes || return 0

    local temp_root render_args agent_name
    temp_root="$STATE_ROOT/tmp"
    mkdir -p "$temp_root"
    PROVIDER_SECTION_DIR="$(mktemp -d "$temp_root/provider-sections.XXXXXX")" || {
        PROVIDER_SECTION_DIR=""
        return 0
    }

    render_args=(render-sections --project-dir "$WORKSPACE_DIR" --output-dir "$PROVIDER_SECTION_DIR")
    for agent_name in "${ACTIVE_PROJECT_AGENT_NAMES[@]}"; do
        render_args+=(--agent-type "$agent_name")
    done

    if ! provider_call agentic-notes "${render_args[@]}" >/dev/null 2>/dev/null; then
        rm -rf "$PROVIDER_SECTION_DIR"
        PROVIDER_SECTION_DIR=""
    fi
}

cleanup_provider_sections() {
    if [[ -n "$PROVIDER_SECTION_DIR" ]]; then
        rm -rf "$PROVIDER_SECTION_DIR"
        PROVIDER_SECTION_DIR=""
    fi
}

valid_agent_name() {
    [[ "$1" =~ ^[A-Za-z0-9._-]+$ ]]
}

render_markdown_agent_file() {
    local source_path="$1"
    local target_path="$2"
    local agent_name="$3"
    local temp_path="${target_path}.tmp"

    awk -v agent_name="$agent_name" '
        BEGIN { inserted=0; in_frontmatter=0 }
        NR == 1 && $0 == "---" { in_frontmatter=1; print; next }
        in_frontmatter && $0 ~ /^[[:space:]]*(kind|codex_reasoning_effort|model_reasoning_effort):[[:space:]]*/ { next }
        in_frontmatter && $0 == "---" {
            print
            print ""
            print "<!-- Generated by agentic-researcher. Edit the source agent definition to change this agent. -->"
            inserted=1
            in_frontmatter=0
            next
        }
        { print }
        END {
            if (inserted == 0) {
                print "<!-- Generated by agentic-researcher. Edit the source agent definition to change this agent. -->"
            }
        }
    ' "$source_path" | expand_modules_from_stdin > "$temp_path"
    {
        printf '\n'
        render_agentic_notes_for_agent_type "$agent_name"
    } >> "$temp_path"

    mv "$temp_path" "$target_path"
}

render_agent_for_tool() {
    cli_call_required render_agent "$@"
}

ACTIVE_PROJECT_AGENT_NAMES=()

add_active_project_agent_name() {
    local agent_name="$1"
    ACTIVE_PROJECT_AGENT_NAMES+=("$agent_name")
}

collect_active_project_agent_names() {
    local source_dir="$1"
    local override_dir="$2"
    local source_path agent_name kind

    [[ -d "$source_dir" ]] || return 0
    for source_path in "$source_dir"/*.md; do
        [[ -f "$source_path" ]] || continue
        agent_name="$(agent_name_for_source "$source_path")"
        if [[ -n "$override_dir" ]] && agent_name_exists_in_source_dir "$agent_name" "$override_dir"; then
            continue
        fi
        [[ -n "$agent_name" ]] || continue
        valid_agent_name "$agent_name" || continue
        kind="$(agent_kind_for_source "$source_path")"
        [[ "$kind" == "subagent" ]] || continue
        add_active_project_agent_name "$agent_name"
    done
}

is_active_project_agent_name() {
    local needle="$1"
    local agent_name

    for agent_name in "${ACTIVE_PROJECT_AGENT_NAMES[@]}"; do
        [[ "$agent_name" == "$needle" ]] && return 0
    done
    return 1
}

cleanup_inactive_managed_agents() {
    local agent_root="$1"
    local managed_marker="$2"
    local target_path target_file agent_name

    [[ -d "$agent_root" ]] || return 0
    for target_path in "$agent_root"/*; do
        [[ -f "$target_path" ]] || continue
        grep -q "$managed_marker" "$target_path" || continue
        target_file="$(basename "$target_path")"
        case "$target_file" in
            *.toml)
                agent_name="${target_file%.toml}"
                ;;
            *.md)
                agent_name="${target_file%.md}"
                ;;
            *)
                continue
                ;;
        esac
        if ! is_active_project_agent_name "$agent_name"; then
            rm -f "$target_path"
        fi
    done
}

render_agent_source_dir() {
    local agent_root="$1"
    local source_dir="$2"
    local source_label="$3"
    local kind_filter="$4"
    local override_dir="${5:-}"
    local managed_marker="Generated by agentic-researcher"
    local source_path agent_name kind description codex_reasoning_effort target_path

    [[ -d "$source_dir" ]] || return 0

    for source_path in "$source_dir"/*.md; do
        [[ -f "$source_path" ]] || continue
        agent_name="$(agent_name_for_source "$source_path")"
        if [[ -n "$override_dir" ]] && agent_name_exists_in_source_dir "$agent_name" "$override_dir"; then
            continue
        fi
        kind="$(agent_kind_for_source "$source_path")"
        if [[ "$kind" != "$kind_filter" ]]; then
            continue
        fi
        description="$(frontmatter_value "$source_path" "description")"
        codex_reasoning_effort="$(frontmatter_value "$source_path" "codex_reasoning_effort")"
        if [[ -z "$codex_reasoning_effort" ]]; then
            codex_reasoning_effort="$(frontmatter_value "$source_path" "model_reasoning_effort")"
        fi
        [[ -n "$description" ]] || description="$agent_name agent."

        if ! valid_agent_name "$agent_name"; then
            echo "Warning: Skipping $source_label agent with invalid name: $agent_name"
            continue
        fi

        target_path="$(cli_call_required agent_target_path "$agent_root" "$agent_name")"
        [[ -n "$target_path" ]] || continue

        if [[ -f "$target_path" ]] && ! grep -q "$managed_marker" "$target_path"; then
            echo "Warning: Skipping $source_label agent at $target_path (not managed by agentic-researcher)"
            continue
        fi

        render_agent_for_tool "$source_path" "$target_path" "$agent_name" "$description" "$codex_reasoning_effort"
    done
}

setup_project_agents() {
    local agent_root org_agent_dir=""
    local render_status=0
    agent_root="$(project_agent_root_for_tool)"
    [[ -n "$agent_root" ]] || return 0

    mkdir -p "$agent_root"

    if [[ -n "${AR_ORG_NOTES_REPO:-}" ]]; then
        org_agent_dir="$STATE_ROOT/repos/org-agentic-notes/agents"
    fi

    ACTIVE_PROJECT_AGENT_NAMES=()
    collect_active_project_agent_names "$SCRIPT_DIR/agents" "$org_agent_dir"
    collect_active_project_agent_names "$org_agent_dir" ""
    cleanup_inactive_managed_agents "$agent_root" "Generated by agentic-researcher"
    prepare_provider_sections

    if ! render_agent_source_dir "$agent_root" "$SCRIPT_DIR/agents" "built-in" "subagent" "$org_agent_dir"; then
        render_status=1
    fi

    if [[ -n "${AR_ORG_NOTES_REPO:-}" ]]; then
        if ! render_agent_source_dir "$agent_root" "$org_agent_dir" "org" "subagent"; then
            render_status=1
        fi
    fi

    cleanup_provider_sections
    return "$render_status"
}

append_skill_instruction_block() {
    local output_path="$1"
    local _skill_name="$2"
    local instruction_source="$3"

    [[ -f "$instruction_source" ]] || return 0

    {
        printf '\n'
        cat "$instruction_source"
    } >> "$output_path"
}

setup_skill_instruction_blocks() {
    local instruction_path="$WORKSPACE_DIR/$INSTRUCTION_TARGET"
    [[ -f "$instruction_path" ]] || return 0

    local temp_path="${instruction_path}.tmp"
    local source_path skill_name

    cp "$instruction_path" "$temp_path"

    for source_path in "$SCRIPT_DIR"/skills/*/INSTRUCTIONS.md; do
        [[ -f "$source_path" ]] || continue
        skill_name="$(basename "$(dirname "$source_path")")"
        append_skill_instruction_block "$temp_path" "$skill_name" "$source_path"
    done

    for skill_name in "${SELECTED_OPTIONAL_SKILLS[@]}"; do
        source_path="$SCRIPT_DIR/optional-skills/$skill_name/INSTRUCTIONS.md"
        append_skill_instruction_block "$temp_path" "$skill_name" "$source_path"
    done

    mv "$temp_path" "$instruction_path"
}

export_instruction_provider_env() {
    if [[ -n "${AR_AGENT_BRANCH_ID:-}" ]]; then
        AR_SESSION_ID="${AR_SESSION_ID:-$AR_PROJECT_ID-$AR_AGENT_BRANCH_ID-$$-$(date +%s)}"
    fi

    export AR_STATE_ROOT AR_ORG_NOTES_REPO AR_MAIN_AGENT AR_INSTRUCTION_PROVIDERS
    export AR_AGENT_BRANCH AR_AGENT_BRANCH_ID AR_AGENT_TOPIC AR_AGENT_BRANCH_PREFIX AR_BRANCH_OWNERSHIP
    export AR_USER_ID AR_PROJECT_ID AR_SESSION_ID
    export AR_AGENTIC_STATE_BRANCH AR_NOTES_AUTO_REFRESH AR_NOTES_REFRESH_MODE AR_NOTES_REFRESH_INTERVAL_SECONDS
    export AR_RESOLVER_GIT_NAME AR_RESOLVER_GIT_EMAIL AR_NOTES_GIT_NAME AR_NOTES_GIT_EMAIL
    export AR_NOTES_CLI AR_TOOL_CLI AR_CLI_TOOL TEST_MODE RENDER_ONLY
    AR_NOTES_CLI="$(ar_notes_cli_host_path)"
    AR_TOOL_CLI="$(ar_tool_cli_host_path)"
}

setup_agentic_notes_provider_once() {
    provider_enabled agentic-notes || return 0
    [[ "$AGENTIC_NOTES_PROVIDER_SETUP" == "true" ]] && return 0

    export_instruction_provider_env
    if ! provider_call agentic-notes setup \
        --project-dir "$WORKSPACE_DIR" \
        --branch "${WORKSPACE_GIT_BRANCH:-}" \
        --session-id "${AR_SESSION_ID:-}" \
        --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
        --tool "$AR_CLI_TOOL"; then
        echo "Error: Instruction provider 'agentic-notes' setup failed."
        exit 1
    fi
    AGENTIC_NOTES_PROVIDER_SETUP=true
}

setup_instruction_providers() {
    local provider_name

    export_instruction_provider_env

    for provider_name in $(enabled_provider_names); do
        if [[ "$provider_name" == "agentic-notes" && "$AGENTIC_NOTES_PROVIDER_SETUP" == "true" ]]; then
            continue
        fi
        if ! provider_call "$provider_name" setup \
            --project-dir "$WORKSPACE_DIR" \
            --branch "${WORKSPACE_GIT_BRANCH:-}" \
            --session-id "${AR_SESSION_ID:-}" \
            --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
            --tool "$AR_CLI_TOOL"; then
            echo "Error: Instruction provider '$provider_name' setup failed."
            exit 1
        fi
    done
}

cleanup_instruction_providers() {
    local provider_name

    export AR_STATE_ROOT AR_ORG_NOTES_REPO AR_MAIN_AGENT AR_INSTRUCTION_PROVIDERS
    export AR_AGENT_BRANCH AR_AGENT_BRANCH_ID AR_AGENT_TOPIC AR_AGENT_BRANCH_PREFIX AR_BRANCH_OWNERSHIP
    export AR_USER_ID AR_PROJECT_ID AR_SESSION_ID
    export AR_AGENTIC_STATE_BRANCH AR_RESOLVER_GIT_NAME AR_RESOLVER_GIT_EMAIL AR_NOTES_GIT_NAME AR_NOTES_GIT_EMAIL
    export AR_NOTES_CLI AR_TOOL_CLI AR_CLI_TOOL TEST_MODE RENDER_ONLY
    AR_NOTES_CLI="$(ar_notes_cli_host_path)"
    AR_TOOL_CLI="$(ar_tool_cli_host_path)"

    for provider_name in $(enabled_provider_names); do
        provider_call "$provider_name" cleanup \
            --project-dir "$WORKSPACE_DIR" \
            --branch "${WORKSPACE_GIT_BRANCH:-}" \
            --session-id "${AR_SESSION_ID:-}" \
            --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
            --tool "$AR_CLI_TOOL" >/dev/null || true
    done
}

launcher_cleanup() {
    local status=$?
    trap - EXIT
    if [[ "$OPTIONAL_CLEANUP_ENABLED" == "true" ]]; then
        run_optional_skill_hooks cleanup || true
    fi
    cleanup_instruction_providers || true
    cleanup_branch_guard || true
    return "$status"
}

setup_provider_refresh_loops() {
    [[ "$TEST_MODE" == "true" ]] && return 0
    [[ "$RENDER_ONLY" == "true" ]] && return 0

    case "${AR_NOTES_AUTO_REFRESH:-true}" in
        0|false|False|FALSE|no|No|NO|off|Off|OFF)
            return 0
            ;;
    esac

    case "${AR_NOTES_REFRESH_MODE:-periodic}" in
        periodic|background)
            ;;
        *)
            return 0
            ;;
    esac

    local interval heartbeat_period heartbeat_dir heartbeat_file refresh_log launcher_pid stale_seconds
    interval="${AR_NOTES_REFRESH_INTERVAL_SECONDS:-120}"
    if ! [[ "$interval" =~ ^[0-9]+$ ]] || [[ "$interval" -lt 1 ]]; then
        interval=120
    fi
    heartbeat_period=$((interval / 4))
    if [[ "$heartbeat_period" -lt 1 ]]; then
        heartbeat_period=1
    elif [[ "$heartbeat_period" -gt 30 ]]; then
        heartbeat_period=30
    fi
    stale_seconds=$((interval * 2))
    if [[ "$stale_seconds" -lt $((heartbeat_period * 3)) ]]; then
        stale_seconds=$((heartbeat_period * 3))
    fi

    heartbeat_dir="$STATE_ROOT/refresh-heartbeats/$AR_PROJECT_ID"
    heartbeat_file="$heartbeat_dir/$$.heartbeat"
    refresh_log="$STATE_ROOT/logs/agentic-notes-refresh-$AR_PROJECT_ID.log"
    launcher_pid="$$"
    mkdir -p "$heartbeat_dir" "$(dirname "$refresh_log")"
    touch "$heartbeat_file"

    (
        while kill -0 "$launcher_pid" 2>/dev/null; do
            touch "$heartbeat_file"
            sleep "$heartbeat_period"
        done
        rm -f "$heartbeat_file"
    ) >/dev/null 2>&1 &

    local provider_name
    for provider_name in $(enabled_provider_names); do
        provider_call "$provider_name" refresh-loop \
            --project-dir "$WORKSPACE_DIR" \
            --heartbeat-dir "$heartbeat_dir" \
            --interval-seconds "$interval" \
            --stale-seconds "$stale_seconds" \
            --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
            --tool "$AR_CLI_TOOL" >>"$refresh_log" 2>&1 &
    done
}

setup_provider_instruction_sections() {
    [[ -n "${INSTRUCTION_TARGET:-}" ]] || return 0
    local instruction_path="$WORKSPACE_DIR/$INSTRUCTION_TARGET"
    local temp_path provider_name section

    [[ -f "$instruction_path" ]] || return 0

    export AR_STATE_ROOT AR_ORG_NOTES_REPO AR_MAIN_AGENT AR_INSTRUCTION_PROVIDERS
    export AR_AGENT_BRANCH AR_AGENT_BRANCH_ID AR_AGENT_TOPIC AR_AGENT_BRANCH_PREFIX AR_BRANCH_OWNERSHIP
    export AR_USER_ID AR_PROJECT_ID AR_SESSION_ID
    export AR_AGENTIC_STATE_BRANCH AR_NOTES_AUTO_REFRESH AR_SANDBOX
    export AR_NOTES_CLI AR_TOOL_CLI AR_CLI_TOOL TEST_MODE RENDER_ONLY
    AR_NOTES_CLI="$(ar_notes_cli_host_path)"
    AR_TOOL_CLI="$(ar_tool_cli_host_path)"

    temp_path="${instruction_path}.tmp"
    cp "$instruction_path" "$temp_path"

    for provider_name in $(enabled_provider_names); do
        section="$(
            provider_call "$provider_name" render-instruction \
                --project-dir "$WORKSPACE_DIR" \
                --agent-type "${AR_MAIN_AGENT:-research-coordinator}" \
                --tool "$AR_CLI_TOOL" 2>/dev/null || true
        )"
        if [[ -n "$section" ]]; then
            {
                printf '\n'
                printf '%s\n' "$section"
            } >> "$temp_path"
        fi
    done

    mv "$temp_path" "$instruction_path"
}

