# Agentic Researcher configuration
# Generated by: agentic-researcher --setup
#
# Location: ${XDG_CONFIG_HOME:-$HOME/.config}/agentic-researcher/config.sh
# Edit individual settings:  agentic-researcher --setup KEY=VALUE

# Runtime: apptainer | docker | podman | native
AR_CONTAINER_RUNTIME="apptainer"

# Authentication: oauth | tool | api-key
# oauth: Claude Code handles login interactively
# tool:  the CLI handles auth inside the container; standard key env vars are passed through
# api-key: launcher validates AR_API_KEY_ENV before launch (mainly useful for Claude)
AR_AUTH_MODE="oauth"

# Optional provider metadata for advanced/custom setups
AR_API_PROVIDER="anthropic"

# Optional env var name for launcher-managed API key validation
AR_API_KEY_ENV="ANTHROPIC_API_KEY"

# For openai-compatible providers: base URL for OpenAI-compatible endpoint
AR_CUSTOM_ENDPOINT=""

# For openai-compatible providers: Anthropic SDK endpoint (used by Claude Code)
AR_CUSTOM_ANTHROPIC_ENDPOINT=""

# CLI tool: claude | opencode | gemini | codex | pi
AR_CLI_TOOL="claude"

# Default model passed to the CLI tool (tool-specific)
AR_DEFAULT_MODEL="sonnet"

# HTTP(S) proxy (leave empty if not needed)
AR_HTTPS_PROXY=""
AR_HTTP_PROXY=""

# Base directory for local state, caches, and container temp data
AR_STATE_ROOT="$HOME/.cache/agentic-researcher"

# Additional directories to bind into the sandbox (colon-separated)
# Accepts commas or spaces too — they get normalized to colons
# Inside the container they appear under /workspace/.mount/<basename>
# Native mode ignores this setting because host paths are already visible
AR_EXTRA_BIND_DIRS=""

# GPU job backend: auto | none | cluster-run | remote-run
# auto uses cluster-run when available in native mode, otherwise none.
# --multi-node selects remote-run for Apptainer + Slurm allocations.
AR_GPU_BACKEND="auto"

# Git URL or local path for organization-wide Agentic Notes.
# Leave empty to use only role/project-local note state.
AR_ORG_NOTES_REPO=""

# Selected top-level main agent, user, and optional project id override.
# By default AR derives project identity from the git origin remote.
# Set AR_PROJECT_ID only when there is no remote or when multiple remotes/forks
# should share one notes and experiment-log state.
AR_MAIN_AGENT="research-coordinator"
AR_USER_ID="$USER"
AR_PROJECT_ID=""

# Durable project state branch and local note refresh behavior.
AR_AGENTIC_STATE_BRANCH="agentic/state"
AR_NOTES_AUTO_REFRESH="true"

# Container images build automatically on first launch when missing.
# Set false to require explicit prebuilds with container/build.sh.
AR_AUTO_BUILD="true"

# Optional Git identity for note-updater and experiment-log commits.
AR_NOTES_GIT_NAME=""
AR_NOTES_GIT_EMAIL=""
