# Agentic Team configuration
# Generated by: agentic-team --setup
#
# Location: ${XDG_CONFIG_HOME:-$HOME/.config}/agentic-team/config.sh
# Edit individual settings:  agentic-team --setup KEY=VALUE

# Sandbox: apptainer | docker | podman | none
AR_SANDBOX="apptainer"

# Authentication: oauth | cli-tool | api-key
# oauth: Claude Code handles login interactively
# cli-tool: the CLI handles auth inside the container; standard key env vars are passed through
# api-key: launcher validates AR_API_KEY_ENV before launch (mainly useful for Claude)
AR_AUTH_MODE="oauth"

# Optional API provider metadata for advanced/custom setups
AR_API_PROVIDER="anthropic"

# Optional env var name for launcher-managed API key validation
AR_API_KEY_ENV="ANTHROPIC_API_KEY"

# For OpenAI-compatible API providers: base URL for OpenAI-compatible endpoint
AR_CUSTOM_ENDPOINT=""

# For OpenAI-compatible API providers: Anthropic SDK endpoint (used by Claude Code)
AR_CUSTOM_ANTHROPIC_ENDPOINT=""

# CLI: claude | opencode | gemini | codex | pi
AR_CLI="claude"

# Default model passed to the selected CLI
AR_DEFAULT_MODEL="sonnet"

# HTTP(S) proxy (leave empty if not needed)
AR_HTTPS_PROXY=""
AR_HTTP_PROXY=""

# Base directory for local state, caches, and container temp data
AR_STATE_ROOT="$HOME/.cache/agentic-team"

# Additional directories to bind into the sandbox (colon-separated)
# Accepts commas or spaces too — they get normalized to colons
# Inside the container they appear under /workspace/.mount/<basename>
# Native mode ignores this setting because host paths are already visible
AR_EXTRA_BIND_DIRS=""

# Enabled capabilities from capabilities/ (comma-separated).
# agentic-notes and experiment-log are enabled by default.
# Add cluster-run or remote-run here when you want those backend capabilities.
AR_CAPABILITIES="agentic-notes,experiment-log"

# Git URL or local path for organization-wide Agentic Notes.
# Leave empty to use only project-local Agentic Notes state.
AR_ORG_NOTES_REPO=""

# Selected top-level main agent and user.
AR_MAIN_AGENT="research-coordinator"
AR_USER_ID="$USER"

# Durable project state branch and local note refresh behavior.
AR_PROJECT_STATE_BRANCH="agentic/project-state"
AR_NOTES_AUTO_REFRESH="true"

# Git identity for Agentic Team-created commits when a repo lacks identity.
AR_GIT_NAME="$USER"
AR_GIT_EMAIL="$USER@example.invalid"

# Container images build automatically on first launch when missing.
# Set false to require explicit prebuilds with container/build.sh.
AR_AUTO_BUILD="true"

# Optional override for Agentic State commits. Blank means use AR_GIT_*.
AR_NOTES_GIT_NAME=""
AR_NOTES_GIT_EMAIL=""
