#!/bin/bash

register_cli_adapter codex 40

cli_codex_apply_defaults() {
    AR_AUTH_MODE="${AR_AUTH_MODE:-tool}"
    AR_API_KEY_ENV="${AR_API_KEY_ENV:-OPENAI_API_KEY}"
}

cli_codex_setup_storage() {
    CODEX_STATE_DIR="$HOME/.codex"
    mkdir -p "$AR_CONFIG_STORE/.codex" "$CODEX_STATE_DIR"
}

cli_codex_instruction_target() {
    printf '%s\n' "AGENTS.md"
}

cli_codex_project_skill_root() {
    printf '%s\n' "$WORKSPACE_DIR/.agents/skills"
}

cli_codex_project_agent_root() {
    printf '%s\n' "$WORKSPACE_DIR/.codex/agents"
}

cli_codex_agent_target_path() {
    printf '%s/%s.toml\n' "$1" "$2"
}

cli_codex_render_agent() {
    local source_path="$1"
    local target_path="$2"
    local agent_name="$3"
    local description="$4"
    local codex_reasoning_effort="$5"
    local temp_path="${target_path}.tmp"
    local name_escaped description_escaped reasoning_escaped

    name_escaped="$(printf '%s' "$agent_name" | toml_escape)"
    description_escaped="$(printf '%s' "$description" | toml_escape)"
    reasoning_escaped="$(printf '%s' "$codex_reasoning_effort" | toml_escape)"
    {
        printf 'name = "%s"\n' "$name_escaped"
        printf 'description = "%s"\n' "$description_escaped"
        if [[ -n "$reasoning_escaped" ]]; then
            printf 'model_reasoning_effort = "%s"\n' "$reasoning_escaped"
        fi
        printf 'developer_instructions = """\n'
        printf '<!-- Generated by agentic-researcher. Edit the source agent definition to change this agent. -->\n\n'
        strip_frontmatter "$source_path" | sed 's/"""/\\"""/g'
        printf '\n'
        render_agentic_notes_for_agent_type "$agent_name" | sed 's/"""/\\"""/g'
        printf '\n"""\n'
    } > "$temp_path"
    mv "$temp_path" "$target_path"
}

cli_codex_setup_compaction_hooks() {
    local script_path="$WORKSPACE_DIR/.codex/hooks/agentic-researcher-compaction.py"
    render_compaction_context_hook_script "$script_path" || return 0

    local script_runtime instruction_runtime notes_cli_runtime project_runtime agent_type_runtime tool_runtime python_runtime command patch_json
    script_runtime="$(workspace_runtime_path ".codex/hooks/agentic-researcher-compaction.py")"
    instruction_runtime="$(workspace_runtime_path "$INSTRUCTION_TARGET")"
    notes_cli_runtime="$(ar_notes_cli_env_path)"
    project_runtime="$(workspace_root_runtime_path)"
    agent_type_runtime="${AR_MAIN_AGENT:-research-coordinator}"
    tool_runtime="$AR_CLI_TOOL"
    python_runtime="$(python_runtime_command_string)"
    command="$python_runtime $(shell_quote "$script_runtime") $(shell_quote "$instruction_runtime") $(shell_quote "$notes_cli_runtime") $(shell_quote "$project_runtime") $(shell_quote "$agent_type_runtime") $(shell_quote "$tool_runtime")"
    patch_json=$(cat <<EOF
{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "compact",
        "hooks": [
          {
            "type": "command",
            "command": $(json_string "$command"),
            "timeout": 120,
            "statusMessage": "Agentic Researcher compaction refresh"
          }
        ]
      }
    ]
  }
}
EOF
)
    if ! merge_managed_hook_json "$WORKSPACE_DIR/.codex/hooks.json" "agentic-researcher-compaction" "$patch_json"; then
        echo "Warning: Could not update Codex compaction hook settings."
    fi
}

cli_codex_translate_tool_args() {
    if [[ "$MODEL_SPECIFIED" == "false" && -n "${AR_DEFAULT_MODEL:-}" ]]; then
        TOOL_ARGS+=("--model" "$AR_DEFAULT_MODEL")
    fi
    if [[ "$YOLO_MODE" == "true" ]]; then
        TOOL_ARGS+=("--dangerously-bypass-approvals-and-sandbox")
    fi
}

cli_codex_add_env_args() {
    append_env_arg_from_host "OPENAI_API_KEY"
    if [[ "${AR_API_KEY_ENV:-OPENAI_API_KEY}" != "OPENAI_API_KEY" ]]; then
        append_env_arg_from_host "${AR_API_KEY_ENV:-OPENAI_API_KEY}"
    fi
    ENV_ARGS+=(--env "SANDBOX_TOOL=codex")
}

cli_codex_add_apptainer_binds() {
    if [[ -d "${CODEX_STATE_DIR:-}" ]]; then
        BIND_ARGS+=(--bind "$CODEX_STATE_DIR:$AR_SANDBOX_HOME/.codex")
    fi
}

cli_codex_add_oci_args() {
    append_oci_env_from_host "OPENAI_API_KEY"
    if [[ "${AR_API_KEY_ENV:-OPENAI_API_KEY}" != "OPENAI_API_KEY" ]]; then
        append_oci_env_from_host "${AR_API_KEY_ENV:-OPENAI_API_KEY}"
    fi
    if [[ -d "${CODEX_STATE_DIR:-}" ]]; then
        OCI_ARGS+=(-v "$CODEX_STATE_DIR:$AR_SANDBOX_HOME/.codex")
    fi
}

cli_codex_native_command() {
    printf '%s\n' "codex"
}

cli_codex_display_name() {
    printf '%s\n' "Codex CLI"
}
