#!/bin/bash

register_cli_adapter codex 40

cli_codex_apply_defaults() {
    AR_AUTH_MODE="${AR_AUTH_MODE:-cli-tool}"
    AR_API_KEY_ENV="${AR_API_KEY_ENV:-OPENAI_API_KEY}"
}

cli_codex_setup_storage() {
    CODEX_STATE_DIR="$HOME/.codex"
    mkdir -p "$AR_CONFIG_STORE/.codex" "$CODEX_STATE_DIR"
}

cli_codex_instruction_target() {
    printf '%s\n' "AGENTS.md"
}

cli_codex_project_skill_root() {
    printf '%s\n' "$WORKSPACE_DIR/.agents/skills"
}

cli_codex_project_agent_root() {
    printf '%s\n' "$WORKSPACE_DIR/.codex/agents"
}

cli_codex_agent_target_path() {
    printf '%s/%s.toml\n' "$1" "$2"
}

cli_codex_render_agent() {
    local source_path="$1"
    local target_path="$2"
    local agent_name="$3"
    local description="$4"
    local codex_reasoning_effort="$5"
    local temp_path="${target_path}.tmp"
    local name_escaped description_escaped reasoning_escaped

    name_escaped="$(printf '%s' "$agent_name" | toml_escape)"
    description_escaped="$(printf '%s' "$description" | toml_escape)"
    reasoning_escaped="$(printf '%s' "$codex_reasoning_effort" | toml_escape)"
    {
        printf 'name = "%s"\n' "$name_escaped"
        printf 'description = "%s"\n' "$description_escaped"
        if [[ -n "$reasoning_escaped" ]]; then
            printf 'model_reasoning_effort = "%s"\n' "$reasoning_escaped"
        fi
        printf 'developer_instructions = """\n'
        printf '<!-- Generated by agentic-team. Edit the source agent definition to change this agent. -->\n\n'
        strip_frontmatter "$source_path" | expand_instruction_modules_from_stdin | sed 's/"""/\\"""/g'
        printf '\n'
        render_agentic_notes_for_agent_type "$agent_name" | sed 's/"""/\\"""/g'
        printf '\n"""\n'
    } > "$temp_path"
    mv "$temp_path" "$target_path"
}

cli_codex_setup_compaction_hooks() {
    local script_path="$WORKSPACE_DIR/.codex/hooks/agentic-team-compaction.py"
    render_compaction_context_hook_script "$script_path" || return 0

    local script_runtime instruction_runtime capability_refresh_runtime project_runtime agent_type_runtime cli_runtime python_runtime post_compact_command patch_json
    script_runtime="$(workspace_runtime_path ".codex/hooks/agentic-team-compaction.py")"
    instruction_runtime="$(workspace_runtime_path "$INSTRUCTION_TARGET")"
    capability_refresh_runtime="$(ar_core_bin_env_path)/capability-refresh"
    project_runtime="$(workspace_root_runtime_path)"
    agent_type_runtime="${AR_MAIN_AGENT:-research-coordinator}"
    cli_runtime="$AR_CLI"
    python_runtime="$(python_runtime_command_string)"
    post_compact_command="$python_runtime $(shell_quote "$script_runtime") post-compact $(shell_quote "$instruction_runtime") $(shell_quote "$capability_refresh_runtime") $(shell_quote "$project_runtime") $(shell_quote "$agent_type_runtime") $(shell_quote "$cli_runtime")"
    patch_json=$(cat <<EOF
{
  "hooks": {
    "PostCompact": [
      {
        "matcher": "manual|auto",
        "hooks": [
          {
            "type": "command",
            "command": $(json_string "$post_compact_command"),
            "timeout": 120,
            "statusMessage": "Agentic Team compaction refresh"
          }
        ]
      }
    ],
    "UserPromptSubmit": [],
    "SessionStart": []
  }
}
EOF
)
    if ! merge_managed_hook_json "$WORKSPACE_DIR/.codex/hooks.json" "agentic-team-compaction" "$patch_json"; then
        echo "Warning: Could not update Codex compaction hook settings."
    fi
}

cli_codex_setup_steering_hooks() {
    local script_path="$WORKSPACE_DIR/.codex/hooks/agentic-team-steering.py"
    render_steering_context_hook_script "$script_path" || return 0

    local script_runtime agentic_notes_runtime project_runtime agent_type_runtime python_runtime command patch_json
    script_runtime="$(workspace_runtime_path ".codex/hooks/agentic-team-steering.py")"
    agentic_notes_runtime="$(agentic_notes_runtime_command)" || return 0
    project_runtime="$(workspace_root_runtime_path)"
    agent_type_runtime="${AR_MAIN_AGENT:-research-coordinator}"
    python_runtime="$(python_runtime_command_string)"
    command="$python_runtime $(shell_quote "$script_runtime") codex-post-tool $(shell_quote "$agentic_notes_runtime") $(shell_quote "$project_runtime") $(shell_quote "$agent_type_runtime")"
    patch_json=$(cat <<EOF
{
  "hooks": {
    "PostToolUse": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": $(json_string "$command"),
            "timeout": 15,
            "statusMessage": "Agentic Notes steering"
          }
        ]
      }
    ]
  }
}
EOF
)
    if ! merge_managed_hook_json "$WORKSPACE_DIR/.codex/hooks.json" "agentic-team-steering" "$patch_json"; then
        echo "Warning: Could not update Codex steering hook settings."
    fi
}

cli_codex_translate_cli_args() {
    local translated=()
    local i arg next

    for ((i=0; i<${#CLI_ARGS[@]}; i++)); do
        arg="${CLI_ARGS[$i]}"
        case "$arg" in
            --resume)
                translated+=("resume")
                next="${CLI_ARGS[$((i+1))]:-}"
                if [[ -n "$next" && ! "$next" =~ ^- ]]; then
                    translated+=("$next")
                    i=$((i + 1))
                fi
                ;;
            --continue)
                translated+=("resume" "--last")
                ;;
            *)
                translated+=("$arg")
                ;;
        esac
    done
    CLI_ARGS=()
    if [[ "$MODEL_SPECIFIED" == "false" && -n "${AR_DEFAULT_MODEL:-}" ]]; then
        CLI_ARGS+=("--model" "$AR_DEFAULT_MODEL")
    fi
    if [[ "$YOLO_MODE" == "true" ]]; then
        CLI_ARGS+=("--dangerously-bypass-approvals-and-sandbox")
    fi
    CLI_ARGS+=("${translated[@]}")
}

cli_codex_add_env_args() {
    append_env_arg_from_host "OPENAI_API_KEY"
    if [[ "${AR_API_KEY_ENV:-OPENAI_API_KEY}" != "OPENAI_API_KEY" ]]; then
        append_env_arg_from_host "${AR_API_KEY_ENV:-OPENAI_API_KEY}"
    fi
    ENV_ARGS+=(--env "SANDBOX_CLI=codex")
}

cli_codex_add_apptainer_binds() {
    if [[ -d "${CODEX_STATE_DIR:-}" ]]; then
        BIND_ARGS+=(--bind "$CODEX_STATE_DIR:$AR_SANDBOX_HOME/.codex")
    fi
}

cli_codex_add_oci_args() {
    append_oci_env_from_host "OPENAI_API_KEY"
    if [[ "${AR_API_KEY_ENV:-OPENAI_API_KEY}" != "OPENAI_API_KEY" ]]; then
        append_oci_env_from_host "${AR_API_KEY_ENV:-OPENAI_API_KEY}"
    fi
    if [[ -d "${CODEX_STATE_DIR:-}" ]]; then
        OCI_ARGS+=(-v "$CODEX_STATE_DIR:$AR_SANDBOX_HOME/.codex")
    fi
}

cli_codex_native_command() {
    printf '%s\n' "codex"
}

cli_codex_display_name() {
    printf '%s\n' "Codex CLI"
}
