#!/bin/bash

register_cli_adapter gemini 30

cli_gemini_apply_defaults() {
    AR_AUTH_MODE="${AR_AUTH_MODE:-tool}"
    AR_API_KEY_ENV="${AR_API_KEY_ENV:-GEMINI_API_KEY}"
}

cli_gemini_setup_storage() {
    GEMINI_STATE_DIR="$HOME/.gemini"
    mkdir -p \
        "$AR_CONFIG_STORE/.gemini/skills" \
        "$AR_CONFIG_STORE/.gemini/agents" \
        "$AR_CONFIG_STORE/.gemini/history" \
        "$AR_CONFIG_STORE/.gemini/tmp/bin" \
        "$GEMINI_STATE_DIR/skills" \
        "$GEMINI_STATE_DIR/agents" \
        "$GEMINI_STATE_DIR/history" \
        "$GEMINI_STATE_DIR/tmp/bin"

    if [[ ! -f "$GEMINI_STATE_DIR/projects.json" ]]; then
        printf '{\n  "projects": {}\n}\n' > "$GEMINI_STATE_DIR/projects.json"
    fi
    if [[ ! -f "$GEMINI_STATE_DIR/settings.json" ]]; then
        printf '{}\n' > "$GEMINI_STATE_DIR/settings.json"
    fi
}

cli_gemini_instruction_target() {
    printf '%s\n' "GEMINI.md"
}

cli_gemini_project_skill_root() {
    printf '%s\n' "$WORKSPACE_DIR/.gemini/skills"
}

cli_gemini_project_agent_root() {
    printf '%s\n' "$WORKSPACE_DIR/.gemini/agents"
}

cli_gemini_agent_target_path() {
    printf '%s/%s.md\n' "$1" "$2"
}

cli_gemini_render_agent() {
    render_markdown_agent_file "$@"
}

render_gemini_compaction_hook_script() {
    local target_path="$1"
    local managed_marker="Generated by agentic-researcher"

    if [[ -f "$target_path" ]] && ! grep -q "$managed_marker" "$target_path"; then
        echo "Warning: Skipping existing Gemini compaction hook script at $target_path (not managed by agentic-researcher)"
        return 1
    fi

    mkdir -p "$(dirname "$target_path")"
    cat > "$target_path" <<'PY'
#!/usr/bin/env python3
# Generated by agentic-researcher. Edit the launcher to change this file.
import json
import subprocess
import sys
import time
from pathlib import Path


def run_command(command: list[str]) -> tuple[bool, str]:
    try:
        result = subprocess.run(command, text=True, capture_output=True, timeout=60)
    except Exception as exc:
        return False, f"{command[0]} did not run: {exc}"
    output = (result.stdout or result.stderr or "").strip()
    if result.returncode == 0:
        return True, output
    return False, output or f"{command[0]} exited with status {result.returncode}."


def run_refresh(provider_refresh_cli: str, instruction_path: str, project_dir: str, agent_type: str, tool: str) -> tuple[bool, str]:
    if not provider_refresh_cli:
        return False, "AR_PROVIDER_REFRESH_CLI was not configured."
    command = [
        provider_refresh_cli,
        "--instruction-path",
        instruction_path,
        "--project-dir",
        project_dir,
        "--agent-type",
        agent_type,
        "--tool",
        tool,
    ]
    return run_command(command)


def refresh_message(instruction_path: str, provider_refresh_cli: str, project_dir: str, agent_type: str, tool: str) -> str:
    refreshed, refresh_status = run_refresh(provider_refresh_cli, instruction_path, project_dir, agent_type, tool)
    refresh_sentence = (
        "Agentic Researcher just refreshed configured instruction providers and rematerialized the rendered instruction file."
        if refreshed
        else f"Agentic Researcher tried to refresh configured instruction providers, but refresh failed: {refresh_status}"
    )
    return (
        "You have just experienced context compaction. Treat this moment as "
        "the new `since the last compaction` boundary for Agentic Notes. "
        f"{refresh_sentence} Before continuing, read "
        f"`{instruction_path}`, the instruction file rendered for this "
        "specific Agentic Researcher invocation, then continue with whatever "
        "task was in progress before compaction. Do not restart from scratch."
    )


def marker_path() -> Path:
    return Path(__file__).with_name(".agentic-researcher-compaction.pending")


def mark_pending(instruction_path: str) -> None:
    try:
        json.load(sys.stdin)
    except Exception:
        pass
    marker_path().write_text(
        json.dumps({"instruction_path": instruction_path, "time": time.time()}) + "\n",
        encoding="utf-8",
    )
    print(json.dumps({
        "systemMessage": "Agentic Researcher will refresh instructions on the next model call.",
        "suppressOutput": True,
    }))


def inject_pending(default_instruction_path: str, provider_refresh_cli: str, project_dir: str, agent_type: str, tool: str) -> None:
    try:
        hook_input = json.load(sys.stdin)
    except Exception:
        hook_input = {}

    marker = marker_path()
    if not marker.exists():
        print("{}")
        return

    try:
        marker_data = json.loads(marker.read_text(encoding="utf-8"))
    except Exception:
        marker_data = {}
    try:
        marker.unlink()
    except FileNotFoundError:
        pass

    instruction_path = marker_data.get("instruction_path") or default_instruction_path
    llm_request = hook_input.get("llm_request")
    if not isinstance(llm_request, dict):
        print("{}")
        return

    messages = llm_request.get("messages")
    if not isinstance(messages, list):
        messages = []

    updated_request = dict(llm_request)
    updated_request["messages"] = messages + [{
        "role": "system",
        "content": refresh_message(str(instruction_path), provider_refresh_cli, project_dir, agent_type, tool),
    }]
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "BeforeModel",
            "llm_request": updated_request,
        },
        "suppressOutput": True,
    }))


def main() -> None:
    mode = sys.argv[1] if len(sys.argv) > 1 else "mark"
    instruction_path = sys.argv[2] if len(sys.argv) > 2 else "GEMINI.md"
    provider_refresh_cli = sys.argv[3] if len(sys.argv) > 3 else ""
    project_dir = sys.argv[4] if len(sys.argv) > 4 else "."
    agent_type = sys.argv[5] if len(sys.argv) > 5 else "research-coordinator"
    tool = sys.argv[6] if len(sys.argv) > 6 else "gemini"
    if mode == "inject":
        inject_pending(instruction_path, provider_refresh_cli, project_dir, agent_type, tool)
    else:
        mark_pending(instruction_path)


if __name__ == "__main__":
    main()
PY
    chmod +x "$target_path"
}

cli_gemini_setup_compaction_hooks() {
    local script_path="$WORKSPACE_DIR/.gemini/hooks/agentic-researcher-compaction.py"
    render_gemini_compaction_hook_script "$script_path" || return 0

    local script_runtime instruction_runtime provider_refresh_runtime project_runtime agent_type_runtime tool_runtime python_runtime mark_command inject_command patch_json
    script_runtime="$(workspace_runtime_path ".gemini/hooks/agentic-researcher-compaction.py")"
    instruction_runtime="$(workspace_runtime_path "$INSTRUCTION_TARGET")"
    provider_refresh_runtime="$(provider_refresh_cli_env_path)"
    project_runtime="$(workspace_root_runtime_path)"
    agent_type_runtime="${AR_MAIN_AGENT:-research-coordinator}"
    tool_runtime="$AR_CLI_TOOL"
    python_runtime="$(python_runtime_command_string)"
    mark_command="$python_runtime $(shell_quote "$script_runtime") mark $(shell_quote "$instruction_runtime") $(shell_quote "$provider_refresh_runtime") $(shell_quote "$project_runtime") $(shell_quote "$agent_type_runtime") $(shell_quote "$tool_runtime")"
    inject_command="$python_runtime $(shell_quote "$script_runtime") inject $(shell_quote "$instruction_runtime") $(shell_quote "$provider_refresh_runtime") $(shell_quote "$project_runtime") $(shell_quote "$agent_type_runtime") $(shell_quote "$tool_runtime")"
    patch_json=$(cat <<EOF
{
  "hooks": {
    "PreCompress": [
      {
        "hooks": [
          {
            "type": "command",
            "command": $(json_string "$mark_command"),
            "name": "Agentic Researcher compaction marker",
            "description": "Marks a compression so the next model request refreshes the rendered instruction file.",
            "timeout": 10000
          }
        ]
      }
    ],
    "BeforeModel": [
      {
        "hooks": [
          {
            "type": "command",
            "command": $(json_string "$inject_command"),
            "name": "Agentic Researcher compaction refresh",
            "description": "After compression, asks the model to read the invocation-specific instruction file and resume work.",
            "timeout": 120000
          }
        ]
      }
    ]
  }
}
EOF
)
    if ! merge_managed_hook_json "$WORKSPACE_DIR/.gemini/settings.json" "agentic-researcher-compaction" "$patch_json"; then
        echo "Warning: Could not update Gemini compaction hook settings."
    fi
}

cli_gemini_translate_tool_args() {
    if [[ "$MODEL_SPECIFIED" == "false" && -n "${AR_DEFAULT_MODEL:-}" ]]; then
        TOOL_ARGS+=("--model" "$AR_DEFAULT_MODEL")
    fi
    if [[ " ${TOOL_ARGS[*]} " != *" --sandbox "* ]]; then
        TOOL_ARGS+=("--sandbox=false")
    fi
    if [[ "$DEBUG_LAUNCH" == "true" ]]; then
        TOOL_ARGS+=("--debug")
    fi
    if [[ "$YOLO_MODE" == "true" ]]; then
        TOOL_ARGS+=("--yolo")
    fi
}

cli_gemini_add_env_args() {
    append_env_arg_from_host "GEMINI_API_KEY"
    append_env_arg_from_host "GOOGLE_API_KEY"
    if [[ "${AR_API_KEY_ENV:-GEMINI_API_KEY}" != "GEMINI_API_KEY" ]]; then
        append_env_arg_from_host "${AR_API_KEY_ENV:-GEMINI_API_KEY}"
    fi
    ENV_ARGS+=(--env "SANDBOX_TOOL=gemini")
}

cli_gemini_add_apptainer_binds() {
    if [[ -d "${GEMINI_STATE_DIR:-}" ]]; then
        BIND_ARGS+=(--bind "$GEMINI_STATE_DIR:$AR_SANDBOX_HOME/.gemini")
    fi
}

cli_gemini_add_oci_args() {
    append_oci_env_from_host "GEMINI_API_KEY"
    append_oci_env_from_host "GOOGLE_API_KEY"
    if [[ "${AR_API_KEY_ENV:-GEMINI_API_KEY}" != "GEMINI_API_KEY" ]]; then
        append_oci_env_from_host "${AR_API_KEY_ENV:-GEMINI_API_KEY}"
    fi
    if [[ -d "${GEMINI_STATE_DIR:-}" ]]; then
        OCI_ARGS+=(-v "$GEMINI_STATE_DIR:$AR_SANDBOX_HOME/.gemini")
    fi
}

cli_gemini_native_command() {
    printf '%s\n' "gemini"
}

cli_gemini_display_name() {
    printf '%s\n' "Gemini CLI"
}
