#!/bin/bash

register_cli_adapter opencode 20

cli_opencode_apply_defaults() {
    AR_AUTH_MODE="${AR_AUTH_MODE:-cli-tool}"
    AR_API_KEY_ENV="${AR_API_KEY_ENV:-OPENAI_API_KEY}"
}

cli_opencode_setup_storage() {
    OPENCODE_STATE_DIR="$STATE_ROOT/opencode"
    OPENCODE_CONFIG_DIR="$OPENCODE_STATE_DIR/config"
    OPENCODE_DATA_DIR="$OPENCODE_STATE_DIR/data"

    mkdir -p \
        "$AR_CONFIG_STORE/.config/opencode" \
        "$AR_CONFIG_STORE/.local/share/opencode" \
        "$AR_CONFIG_STORE/.opencode/bin" \
        "$OPENCODE_CONFIG_DIR" \
        "$OPENCODE_DATA_DIR"
}

cli_opencode_instruction_target() {
    printf '%s\n' "AGENTS.md"
}

cli_opencode_project_skill_root() {
    printf '%s\n' "$WORKSPACE_DIR/.opencode/skills"
}

cli_opencode_project_agent_root() {
    printf '%s\n' "$WORKSPACE_DIR/.opencode/agents"
}

cli_opencode_agent_target_path() {
    printf '%s/%s.md\n' "$1" "$2"
}

cli_opencode_render_agent() {
    local source_path="$1"
    local target_path="$2"
    local agent_name="$3"
    local description="$4"
    local temp_path="${target_path}.tmp"
    local body_path="${target_path}.body.tmp"
    local description_escaped

    if ! render_expanded_agent_body "$source_path" > "$body_path"; then
        rm -f "$body_path"
        return 1
    fi

    description_escaped="$(printf '%s' "$description" | toml_escape)"
    {
        printf -- '---\n'
        printf 'description: "%s"\n' "$description_escaped"
        printf 'mode: subagent\n'
        printf -- '---\n\n'
        printf '<!-- Generated by agentic-team. Edit the source agent definition to change this agent. -->\n\n'
        cat "$body_path"
        printf '\n'
        render_agentic_notes_for_agent_type "$agent_name"
    } > "$temp_path"
    rm -f "$body_path"
    mv "$temp_path" "$target_path"
}

cli_opencode_setup_compaction_hooks() {
    local plugin_path="$WORKSPACE_DIR/.opencode/plugins/agentic-team-compaction.ts"
    local managed_marker="Generated by agentic-team"
    local instruction_runtime capability_refresh_runtime project_runtime agent_type_runtime cli_runtime refresh_context

    if [[ -f "$plugin_path" ]] && ! grep -q "$managed_marker" "$plugin_path"; then
        echo "Warning: Skipping existing OpenCode compaction plugin at $plugin_path (not managed by agentic-team)"
        return 0
    fi

    instruction_runtime="$(workspace_runtime_path "$INSTRUCTION_TARGET")"
    capability_refresh_runtime="$(ar_core_bin_env_path)/capability-refresh"
    project_runtime="$(workspace_root_runtime_path)"
    agent_type_runtime="${AR_MAIN_AGENT:-research-coordinator}"
    cli_runtime="$AR_CLI"
    refresh_context="## Agentic Team Post-Compaction Refresh

The continuing model must be told: You have just experienced context compaction. Treat this moment as the new \`since the last compaction\` boundary for Agentic Notes. Agentic Team just refreshed configured capabilities and rematerialized the rendered instruction file. Before continuing, read \`$instruction_runtime\`, the instruction file rendered for this specific Agentic Team invocation, then continue with whatever task was in progress before compaction. Do not restart from scratch."
    mkdir -p "$(dirname "$plugin_path")"
    cat > "$plugin_path" <<EOF
// Generated by agentic-team. Edit the launcher to change this file.
import { execFileSync } from "node:child_process"
import type { Plugin } from "@opencode-ai/plugin"

const refreshContext = $(json_string "$refresh_context")
const capabilityRefreshCli = $(json_string "$capability_refresh_runtime")
const instructionPath = $(json_string "$instruction_runtime")
const projectDir = $(json_string "$project_runtime")
const agentType = $(json_string "$agent_type_runtime")
const cli = $(json_string "$cli_runtime")

function runRefresh(): string {
  try {
    const refresh = execFileSync(capabilityRefreshCli, [
      "--instruction-path",
      instructionPath,
      "--project-dir",
      projectDir,
      "--agent-type",
      agentType,
      "--cli",
      cli,
    ], { encoding: "utf8", timeout: 60000 }).trim()
    return refresh || "Capabilities refreshed."
  } catch (error) {
    return \`Capability refresh failed: \${error}\`
  }
}

export const AgenticTeamCompactionPlugin: Plugin = async () => {
  return {
    "experimental.session.compacting": async (_input, output) => {
      output.context.push(\`\${refreshContext}\n\nRefresh status: \${runRefresh()}\`)
    },
  }
}
EOF
}

cli_opencode_setup_tool_transport() {
    local tool_mcp_command workflow_mcp_command patch_json tool_server workflow_server
    if enabled_capabilities_have_tools; then
        tool_mcp_command="$(agentic_tools_mcp_runtime_command)"
        tool_server=$(cat <<EOF
{
      "type": "local",
      "command": [$(json_string "$tool_mcp_command")],
      "enabled": true
}
EOF
)
    else
        tool_server=null
    fi
    if workflow_mcp_command="$(imperative_workflows_mcp_runtime_command)"; then
        workflow_server=$(cat <<EOF
{
  "type": "local",
  "command": [$(json_string "$workflow_mcp_command")],
  "enabled": true
}
EOF
)
    else
        workflow_server=null
    fi
    patch_json=$(cat <<EOF
{"mcp":{"agentic_tools":$tool_server,"agentic_workflows":$workflow_server}}
EOF
)
    merge_managed_hook_json \
        "$WORKSPACE_DIR/opencode.json" \
        "agentic-team-tools" \
        "$patch_json"
}

cli_opencode_translate_cli_args() {
    local translated=()
    local skip_next=false
    local i arg next
    for ((i=0; i<${#CLI_ARGS[@]}; i++)); do
        if [[ "$skip_next" == "true" ]]; then
            skip_next=false
            continue
        fi
        arg="${CLI_ARGS[$i]}"
        case "$arg" in
            --dangerously-skip-permissions)
                echo "Warning: --yolo has no effect in OpenCode mode"
                ;;
            --resume)
                next="${CLI_ARGS[$((i+1))]:-}"
                if [[ -n "$next" && ! "$next" =~ ^- ]]; then
                    translated+=("--session" "$next")
                    skip_next=true
                else
                    echo "Warning: --resume without ID not supported in OpenCode"
                fi
                ;;
            --context)
                skip_next=true
                echo "Warning: --context not supported in OpenCode"
                ;;
            *)
                translated+=("$arg")
                ;;
        esac
    done
    CLI_ARGS=("${translated[@]}")
    if [[ "$MODEL_SPECIFIED" == "false" && -n "${AR_DEFAULT_MODEL:-}" ]]; then
        CLI_ARGS+=("--model" "$AR_DEFAULT_MODEL")
    fi
    if [[ "$DEBUG_LAUNCH" == "true" ]]; then
        CLI_ARGS+=("--print-logs" "--log-level" "DEBUG")
    fi
    if [[ "$YOLO_MODE" == "true" ]]; then
        echo "Warning: --yolo has no effect in OpenCode mode (no permission system)"
    fi
}

cli_opencode_setup_runtime() {
    [[ "$AR_SANDBOX" != "none" ]] || return 0
    mkdir -p "$OPENCODE_DATA_DIR" "$OPENCODE_CONFIG_DIR"

    local oc_config="$OPENCODE_CONFIG_DIR/opencode.json"
    if [[ -n "${AR_CUSTOM_ENDPOINT:-}" && -f "$SCRIPT_DIR/config/opencode_config.template.json" ]]; then
        local api_key_var="${AR_API_KEY_ENV:-OPENAI_API_KEY}"
        local api_key="${!api_key_var:-}"
        sed -e "s|__AR_CUSTOM_ENDPOINT__|$AR_CUSTOM_ENDPOINT|g" \
            -e "s|__AR_API_KEY__|$api_key|g" \
            "$SCRIPT_DIR/config/opencode_config.template.json" > "$oc_config"
    fi
}

cli_opencode_add_env_args() {
    append_env_arg_from_host "OPENAI_API_KEY"
    if [[ "${AR_API_KEY_ENV:-OPENAI_API_KEY}" != "OPENAI_API_KEY" ]]; then
        append_env_arg_from_host "${AR_API_KEY_ENV:-OPENAI_API_KEY}"
    fi
    ENV_ARGS+=(--env "SANDBOX_CLI=opencode")
}

cli_opencode_add_apptainer_binds() {
    if [[ -d "${OPENCODE_CONFIG_DIR:-}" ]]; then
        BIND_ARGS+=(--bind "$OPENCODE_CONFIG_DIR:$AR_SANDBOX_HOME/.config/opencode")
    fi
    if [[ -d "${OPENCODE_DATA_DIR:-}" ]]; then
        BIND_ARGS+=(--bind "$OPENCODE_DATA_DIR:$AR_SANDBOX_HOME/.local/share/opencode")
    fi
}

cli_opencode_add_oci_args() {
    append_oci_env_from_host "OPENAI_API_KEY"
    if [[ "${AR_API_KEY_ENV:-OPENAI_API_KEY}" != "OPENAI_API_KEY" ]]; then
        append_oci_env_from_host "${AR_API_KEY_ENV:-OPENAI_API_KEY}"
    fi
    if [[ -d "${OPENCODE_CONFIG_DIR:-}" ]]; then
        OCI_ARGS+=(-v "$OPENCODE_CONFIG_DIR:$AR_SANDBOX_HOME/.config/opencode")
    fi
    if [[ -d "${OPENCODE_DATA_DIR:-}" ]]; then
        OCI_ARGS+=(-v "$OPENCODE_DATA_DIR:$AR_SANDBOX_HOME/.local/share/opencode")
    fi
}

cli_opencode_native_command() {
    printf '%s\n' "opencode"
}

cli_opencode_display_name() {
    printf '%s\n' "OpenCode"
}
