#!/bin/bash

register_cli_adapter pi 50

cli_pi_apply_defaults() {
    AR_AUTH_MODE="${AR_AUTH_MODE:-tool}"
    AR_API_KEY_ENV="${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
}

cli_pi_setup_storage() {
    PI_STATE_DIR="$HOME/.pi"
    mkdir -p "$AR_CONFIG_STORE/.pi/agent" "$PI_STATE_DIR/agent"
}

cli_pi_instruction_target() {
    printf '%s\n' "AGENTS.md"
}

cli_pi_project_skill_root() {
    printf '%s\n' "$WORKSPACE_DIR/.agents/skills"
}

cli_pi_project_agent_root() {
    :
}

cli_pi_agent_target_path() {
    :
}

cli_pi_render_agent() {
    :
}

cli_pi_setup_compaction_hooks() {
    local extension_path="$WORKSPACE_DIR/.pi/extensions/agentic-researcher-compaction.ts"
    local managed_marker="Generated by agentic-researcher"
    local instruction_runtime extension_runtime provider_refresh_runtime project_runtime agent_type_runtime tool_runtime refresh_message

    if [[ -f "$extension_path" ]] && ! grep -q "$managed_marker" "$extension_path"; then
        echo "Warning: Skipping existing pi compaction extension at $extension_path (not managed by agentic-researcher)"
        return 0
    fi

    instruction_runtime="$(workspace_runtime_path "$INSTRUCTION_TARGET")"
    extension_runtime="$(workspace_runtime_path ".pi/extensions/agentic-researcher-compaction.ts")"
    provider_refresh_runtime="$(provider_refresh_cli_env_path)"
    project_runtime="$(workspace_root_runtime_path)"
    agent_type_runtime="${AR_MAIN_AGENT:-research-coordinator}"
    tool_runtime="$AR_CLI_TOOL"
    refresh_message="You have just experienced context compaction. Treat this moment as the new \`since the last compaction\` boundary for Agentic Notes. Agentic Researcher just refreshed configured instruction providers and rematerialized the rendered instruction file. Before continuing, read \`$instruction_runtime\`, the instruction file rendered for this specific Agentic Researcher invocation, then continue with whatever task was in progress before compaction. Do not restart from scratch."
    mkdir -p "$(dirname "$extension_path")"
    cat > "$extension_path" <<EOF
// Generated by agentic-researcher. Edit the launcher to change this file.
import { execFileSync } from "node:child_process"
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent"

const refreshMessage = $(json_string "$refresh_message")
const providerRefreshCli = $(json_string "$provider_refresh_runtime")
const instructionPath = $(json_string "$instruction_runtime")
const projectDir = $(json_string "$project_runtime")
const agentType = $(json_string "$agent_type_runtime")
const tool = $(json_string "$tool_runtime")

function runRefresh(): string {
  try {
    const refresh = execFileSync(providerRefreshCli, [
      "--instruction-path",
      instructionPath,
      "--project-dir",
      projectDir,
      "--agent-type",
      agentType,
      "--tool",
      tool,
    ], { encoding: "utf8", timeout: 60000 }).trim()
    return refresh || "Instruction providers refreshed."
  } catch (error) {
    return \`Instruction provider refresh failed: \${error}\`
  }
}

export default function (pi: ExtensionAPI): void {
  let pendingRefresh = false

  pi.on("session_compact", async () => {
    pendingRefresh = true
  })

  pi.on("context", async (event) => {
    if (!pendingRefresh) return
    pendingRefresh = false
    const message = \`\${refreshMessage}\n\nRefresh status: \${runRefresh()}\`
    return {
      messages: [
        ...event.messages,
        {
          role: "custom",
          customType: "agentic-researcher-compaction-refresh",
          content: message,
          display: false,
          timestamp: Date.now(),
        },
      ],
    }
  })

  pi.on("before_agent_start", async () => {
    if (!pendingRefresh) return
    pendingRefresh = false
    const message = \`\${refreshMessage}\n\nRefresh status: \${runRefresh()}\`
    return {
      message: {
        customType: "agentic-researcher-compaction-refresh",
        content: message,
        display: false,
      },
    }
  })
}
EOF

    PI_AGENTIC_COMPACTION_EXTENSION="$extension_runtime"
}

cli_pi_translate_tool_args() {
    local translated=()
    local skip_next=false
    local i arg next
    for ((i=0; i<${#TOOL_ARGS[@]}; i++)); do
        if [[ "$skip_next" == "true" ]]; then
            skip_next=false
            continue
        fi
        arg="${TOOL_ARGS[$i]}"
        case "$arg" in
            --dangerously-skip-permissions)
                echo "Warning: --yolo has no effect in pi mode (no permission system)"
                ;;
            --resume)
                next="${TOOL_ARGS[$((i+1))]:-}"
                if [[ -n "$next" && ! "$next" =~ ^- ]]; then
                    translated+=("--session" "$next")
                    skip_next=true
                else
                    translated+=("--resume")
                fi
                ;;
            --context)
                skip_next=true
                echo "Warning: --context not supported in pi"
                ;;
            *)
                translated+=("$arg")
                ;;
        esac
    done
    TOOL_ARGS=("${translated[@]}")
    if [[ "$MODEL_SPECIFIED" == "false" && -n "${AR_DEFAULT_MODEL:-}" ]]; then
        TOOL_ARGS+=("--model" "$AR_DEFAULT_MODEL")
    fi
    if [[ "$DEBUG_LAUNCH" == "true" ]]; then
        TOOL_ARGS+=("--verbose")
    fi
    if [[ -n "${PI_AGENTIC_COMPACTION_EXTENSION:-}" ]]; then
        TOOL_ARGS+=("-e" "$PI_AGENTIC_COMPACTION_EXTENSION")
    fi
    if [[ "$YOLO_MODE" == "true" ]]; then
        echo "Warning: --yolo has no effect in pi mode (no permission system)"
    fi
}

cli_pi_add_env_args() {
    append_env_arg_from_host "ANTHROPIC_API_KEY"
    if [[ "${AR_AUTH_MODE:-}" == "api-key" ]]; then
        append_env_arg_from_host_as "ANTHROPIC_API_KEY" "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    elif [[ "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}" != "ANTHROPIC_API_KEY" ]]; then
        append_env_arg_from_host "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    fi
    ENV_ARGS+=(--env "SANDBOX_TOOL=pi")
}

cli_pi_add_oci_args() {
    append_oci_env_from_host "ANTHROPIC_API_KEY"
    if [[ "${AR_AUTH_MODE:-}" == "api-key" ]]; then
        append_oci_env_from_host_as "ANTHROPIC_API_KEY" "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    elif [[ "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}" != "ANTHROPIC_API_KEY" ]]; then
        append_oci_env_from_host "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    fi
}

cli_pi_setup_native_environment() {
    if [[ "${AR_AUTH_MODE:-}" == "api-key" ]]; then
        export_env_from_host_as "ANTHROPIC_API_KEY" "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    fi
}

cli_pi_add_apptainer_binds() {
    if [[ -d "${PI_STATE_DIR:-}" ]]; then
        BIND_ARGS+=(--bind "$PI_STATE_DIR:$AR_SANDBOX_HOME/.pi")
    fi
}

cli_pi_native_command() {
    printf '%s\n' "pi"
}

cli_pi_display_name() {
    printf '%s\n' "pi"
}
