#!/bin/bash

register_cli_adapter pi 50

cli_pi_apply_defaults() {
    AR_AUTH_MODE="${AR_AUTH_MODE:-cli-tool}"
    AR_API_KEY_ENV="${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
}

cli_pi_setup_storage() {
    PI_STATE_DIR="$HOME/.pi"
    mkdir -p "$AR_CONFIG_STORE/.pi/agent" "$PI_STATE_DIR/agent"
}

cli_pi_instruction_target() {
    printf '%s\n' "AGENTS.md"
}

cli_pi_project_skill_root() {
    printf '%s\n' "$WORKSPACE_DIR/.agents/skills"
}

cli_pi_project_agent_root() {
    :
}

cli_pi_agent_target_path() {
    :
}

cli_pi_render_agent() {
    :
}

cli_pi_setup_compaction_hooks() {
    local extension_path="$WORKSPACE_DIR/.pi/extensions/agentic-team-compaction.ts"
    local managed_marker="Generated by agentic-team"
    local instruction_runtime extension_runtime capability_refresh_runtime project_runtime agent_type_runtime cli_runtime refresh_message

    if [[ -f "$extension_path" ]] && ! grep -q "$managed_marker" "$extension_path"; then
        echo "Warning: Skipping existing pi compaction extension at $extension_path (not managed by agentic-team)"
        return 0
    fi

    instruction_runtime="$(workspace_runtime_path "$INSTRUCTION_TARGET")"
    extension_runtime="$(workspace_runtime_path ".pi/extensions/agentic-team-compaction.ts")"
    capability_refresh_runtime="$(ar_core_bin_env_path)/capability-refresh"
    project_runtime="$(workspace_root_runtime_path)"
    agent_type_runtime="$AR_MAIN_AGENT"
    cli_runtime="$AR_CLI"
    refresh_message="You have just experienced context compaction. Treat this moment as the new \`since the last compaction\` boundary for Agentic Notes. Agentic Team just refreshed configured capabilities and rematerialized the rendered instruction file. Before continuing, read \`$instruction_runtime\`, the instruction file rendered for this specific Agentic Team invocation, then continue with whatever task was in progress before compaction. Do not restart from scratch."
    mkdir -p "$(dirname "$extension_path")"
    cat > "$extension_path" <<EOF
// Generated by agentic-team. Edit the launcher to change this file.
import { execFileSync } from "node:child_process"
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent"

const refreshMessage = $(json_string "$refresh_message")
const capabilityRefreshCli = $(json_string "$capability_refresh_runtime")
const instructionPath = $(json_string "$instruction_runtime")
const projectDir = $(json_string "$project_runtime")
const agentType = $(json_string "$agent_type_runtime")
const cli = $(json_string "$cli_runtime")

function runRefresh(): string {
  try {
    const refresh = execFileSync(capabilityRefreshCli, [
      "--instruction-path",
      instructionPath,
      "--project-dir",
      projectDir,
      "--agent-type",
      agentType,
      "--cli",
      cli,
    ], { encoding: "utf8", timeout: 60000 }).trim()
    return refresh || "Capabilities refreshed."
  } catch (error) {
    return \`Capability refresh failed: \${error}\`
  }
}

export default function (pi: ExtensionAPI): void {
  let pendingRefresh = false

  pi.on("session_compact", async () => {
    pendingRefresh = true
  })

  pi.on("context", async (event) => {
    if (!pendingRefresh) return
    pendingRefresh = false
    const message = \`\${refreshMessage}\n\nRefresh status: \${runRefresh()}\`
    return {
      messages: [
        ...event.messages,
        {
          role: "custom",
          customType: "agentic-team-compaction-refresh",
          content: message,
          display: false,
          timestamp: Date.now(),
        },
      ],
    }
  })

  pi.on("before_agent_start", async () => {
    if (!pendingRefresh) return
    pendingRefresh = false
    const message = \`\${refreshMessage}\n\nRefresh status: \${runRefresh()}\`
    return {
      message: {
        customType: "agentic-team-compaction-refresh",
        content: message,
        display: false,
      },
    }
  })
}
EOF

    PI_AGENTIC_COMPACTION_EXTENSION="$extension_runtime"
}

cli_pi_setup_tool_transport() {
    local workflow_mcp_command patch_json workflow_server
    if workflow_mcp_command="$(imperative_workflows_mcp_runtime_command)"; then
        workflow_server=$(cat <<EOF
{
  "transport": "stdio",
  "command": $(json_string "$workflow_mcp_command"),
  "lifecycle": "eager",
  "requestTimeoutMs": 3600000
}
EOF
)
    else
        workflow_server=null
    fi
    if [[ "$workflow_server" != null ]]; then
        PI_AGENTIC_TOOLS_EXTENSION="${AR_PI_MCP_EXTENSION_SPEC:-npm:pi-mcp-extension@1.5.0}"
    else
        PI_AGENTIC_TOOLS_EXTENSION=""
    fi
    patch_json=$(cat <<EOF
{"mcpServers":{"agentic_tools":null,"agentic_workflows":$workflow_server}}
EOF
)
    merge_managed_hook_json \
        "$WORKSPACE_DIR/.pi/mcp.json" \
        "agentic-team-tools" \
        "$patch_json"
}

cli_pi_translate_cli_args() {
    local translated=()
    local skip_next=false
    local i arg next
    for ((i=0; i<${#CLI_ARGS[@]}; i++)); do
        if [[ "$skip_next" == "true" ]]; then
            skip_next=false
            continue
        fi
        arg="${CLI_ARGS[$i]}"
        case "$arg" in
            --dangerously-skip-permissions)
                echo "Warning: --yolo has no effect in pi mode (no permission system)"
                ;;
            --resume)
                next="${CLI_ARGS[$((i+1))]:-}"
                if [[ -n "$next" && ! "$next" =~ ^- ]]; then
                    translated+=("--session" "$next")
                    skip_next=true
                else
                    translated+=("--resume")
                fi
                ;;
            --context)
                skip_next=true
                echo "Warning: --context not supported in pi"
                ;;
            *)
                translated+=("$arg")
                ;;
        esac
    done
    CLI_ARGS=("${translated[@]}")
    if [[ "$MODEL_SPECIFIED" == "false" && -n "${AR_DEFAULT_MODEL:-}" ]]; then
        CLI_ARGS+=("--model" "$AR_DEFAULT_MODEL")
    fi
    if [[ "$DEBUG_LAUNCH" == "true" ]]; then
        CLI_ARGS+=("--verbose")
    fi
    if [[ -n "${PI_AGENTIC_COMPACTION_EXTENSION:-}" ]]; then
        CLI_ARGS+=("-e" "$PI_AGENTIC_COMPACTION_EXTENSION")
    fi
    if [[ -n "${PI_AGENTIC_TOOLS_EXTENSION:-}" ]]; then
        CLI_ARGS+=("-e" "$PI_AGENTIC_TOOLS_EXTENSION")
    fi
    if [[ "$YOLO_MODE" == "true" ]]; then
        echo "Warning: --yolo has no effect in pi mode (no permission system)"
    fi
}

cli_pi_add_env_args() {
    append_env_arg_from_host "ANTHROPIC_API_KEY"
    if [[ "${AR_AUTH_MODE:-}" == "api-key" ]]; then
        append_env_arg_from_host_as "ANTHROPIC_API_KEY" "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    elif [[ "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}" != "ANTHROPIC_API_KEY" ]]; then
        append_env_arg_from_host "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    fi
    ENV_ARGS+=(--env "SANDBOX_CLI=pi")
}

cli_pi_add_oci_args() {
    append_oci_env_from_host "ANTHROPIC_API_KEY"
    if [[ "${AR_AUTH_MODE:-}" == "api-key" ]]; then
        append_oci_env_from_host_as "ANTHROPIC_API_KEY" "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    elif [[ "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}" != "ANTHROPIC_API_KEY" ]]; then
        append_oci_env_from_host "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    fi
}

cli_pi_setup_native_environment() {
    if [[ "${AR_AUTH_MODE:-}" == "api-key" ]]; then
        export_env_from_host_as "ANTHROPIC_API_KEY" "${AR_API_KEY_ENV:-ANTHROPIC_API_KEY}"
    fi
}

cli_pi_add_apptainer_binds() {
    if [[ -d "${PI_STATE_DIR:-}" ]]; then
        BIND_ARGS+=(--bind "$PI_STATE_DIR:$AR_SANDBOX_HOME/.pi")
    fi
}

cli_pi_native_command() {
    printf '%s\n' "pi"
}

cli_pi_display_name() {
    printf '%s\n' "pi"
}
